### ISSUE TITLE
[Help] Error adding entities for domain sensor

### ISSUE THREAD

**Issue by jsbowling42** [jeroenterheerdt/HAsmartirrigation#115]
not sure what this error means, any help would be appreciated.

2022-11-06 21:59:03.100 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform smart_irrigation
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
if (state := self.state) is None:
File "/config/custom_components/smart_irrigation/sensor.py", line 557, in state
self._state = self.update_state()
File "/config/custom_components/smart_irrigation/sensor.py", line 366, in update_state
data = self.coordinator.data["daily"][0]
TypeError: 'NoneType' object is not subscriptable

**Comment by jsbowling42** [comment]
Duplicate
