### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by corbinianbenkiser** [jeroenterheerdt/HAsmartirrigation#128]
**Describe the bug**
Can't get the daily adjusted runtime to show anything else than 0.

**To Reproduce**
1. Install with all OWM except the precipititaion sensor
2. Try to calculate the adjusted data using the service

**Expected behavior**
it calculates the adjusted_runtime_daily

**Error Message from LOG**

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 204, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 349, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 146, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/smart_irrigation/sensor.py", line 557, in state
    self._state = self.update_state()
  File "/config/custom_components/smart_irrigation/sensor.py", line 366, in update_state
    data = self.coordinator.data["daily"][0]
TypeError: 'NoneType' object is not subscriptable

also there might be a problem with the OWM connection
Logger: custom_components.smart_irrigation.OWMClient
Source: custom_components/smart_irrigation/OWMClient.py:78 
Integration: Smart Irrigation ([documentation](https://github.com/jeroenterheerdt/HASmartIrrigation), [issues](https://github.com/jeroenterheerdt/HASmartIrrigation/issues)) 
First occurred: 10:22:38 (1 occurrences) 
Last logged: 10:22:38

Cannot talk to OWM API, check API key.

**Comment by jeroenterheerdt** [comment]
please use the latest version (0.0.79) and see if it resolves this issue.

**Comment by hutterm** [comment]
I think this is still the same issue with a slightly different stacktrace though:
```
2023-07-07 16:26:18.488 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform smart_irrigation
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 632, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _stringify_state
if (state := self.state) is None:
File "/config/custom_components/smart_irrigation/sensor.py", line 557, in state
self._state = self.update_state()
File "/config/custom_components/smart_irrigation/sensor.py", line 366, in update_state
data = self.coordinator.data["daily"][0]
TypeError: 'NoneType' object is not subscriptable
2023-07-07 16:26:18.712 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up smart_irrigation platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 312, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 632, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _stringify_state
if (state := self.state) is None:
File "/config/custom_components/smart_irrigation/sensor.py", line 557, in state
self._state = self.update_state()
File "/config/custom_components/smart_irrigation/sensor.py", line 366, in update_state
data = self.coordinator.data["daily"][0]
TypeError: 'NoneType' object is not subscriptable
```

I'm on the latest 0.0.79

**Comment by jeroenterheerdt** [comment]
version 2.0 is now in beta, please install it and confirm this issue is resolved there.

**Comment by gatonero** [comment]
This issue is not v2.0 related and doesn't exist there and should get closed.
