### ISSUE TITLE
[Bug] Integration stopped working with 2023.6.0b0

### ISSUE THREAD

**Issue by bobvmierlo** [jeroenterheerdt/HAsmartirrigation#130]
**Describe the bug**
See errors from HA:
```
Logger: homeassistant.setup
Source: setup.py:374
First occurred: 22:40:11 (1 occurrences)
Last logged: 22:40:11

Unable to prepare setup for platform smart_irrigation.sensor: Platform not found (Exception importing custom_components.smart_irrigation.sensor).
```

```
This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/smart_irrigation/sensor.py:124
Integration: Smart Irrigation (documentation, issues)
First occurred: 22:40:11 (1 occurrences)
Last logged: 22:40:11

Unexpected exception importing platform custom_components.smart_irrigation.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/smart_irrigation/sensor.py", line 102, in <module>
    class SmartIrrigationSensor(SmartIrrigationEntity):
  File "/config/custom_components/smart_irrigation/sensor.py", line 124, in SmartIrrigationSensor
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'
```

**Installed version**
Which version of the component are you running? 
v0.0.78

**Comment by ScratMan** [comment]
@bobvmierlo could you please try by editing the python file in your Home Assistant configuration folder 
.homeassistant/custom_components/smart_irrigation/sensor.py
At line 124, you will find a line starting with @asyncio.coroutine ; just add a # in front of the @ , save the file and restart HA. Then check if it solves the issue.
Thanks

**Comment by bobvmierlo** [comment]
Works like a charm @ScratMan, is this a permanent fix?

**Comment by ScratMan** [comment]
> Works like a charm @ScratMan, is this a permanent fix?

It will remain until an update is available for the integration, so you can keep it and wait for the next update.

**Comment by rrozema** [comment]
I have the same error since the offical release of HA 2023.6.0. When will the fixed integration be available in HACS?

**Comment by mattfox27** [comment]
not working for me either

**Comment by jeroenterheerdt** [comment]
So sorry all, life got in the way. I will try to fix this next week.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mattfox27** [comment]
No worries, just looks like a cool project, thanks for development its appreciated
