### ISSUE TITLE
[Bug] module 'asyncio' has no attribute 'coroutine'

### ISSUE THREAD

**Issue by jsbowling42** [jeroenterheerdt/HAsmartirrigation#133]
This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/smart_irrigation/sensor.py:124 
Integration: Smart Irrigation (documentation, issues) 
First occurred: 4:26:05 PM (8 occurrences) 
Last logged: 4:26:05 PM

Unexpected exception importing platform custom_components.smart_irrigation.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/smart_irrigation/sensor.py", line 102, in <module>
    class SmartIrrigationSensor(SmartIrrigationEntity):
  File "/config/custom_components/smart_irrigation/sensor.py", line 124, in SmartIrrigationSensor
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'

**Comment by koldogut** [comment]
Same here, this happens when upgrading to HA version 2023.06

**Comment by ScratMan** [comment]
The issues is understood but we are waiting for a merge of the fix. Please refer to #130 as you may edit the file yourself locally to fix it till the official update.

**Comment by jeroenterheerdt** [comment]
https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v.0.0.79
