### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lupinve** [jeroenterheerdt/HAsmartirrigation#137]
Hi, 

it's the same bug o is it a my problem :) ?

Thnaks

Logger: homeassistant.config_entries
Source: custom_components/smart_irrigation/__init__.py:121
Integration: Smart Irrigation (documentation, issues)
First occurred: 11:50:54 (2 occurrences)
Last logged: 12:26:08

Error setting up entry Smart Irrigation for smart_irrigation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 121, in async_setup_entry
    precipitation_rate = (throughput * 60) / area
                         ~~~~~~~~~~~~~~~~^~~~~~~~
ZeroDivisionError: float division by zero

**Comment by lupinve** [comment]
This the complete log. Please help

 might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-15 22:46:15.220 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-15 22:46:15.223 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration reolink_dev which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-15 22:46:15.229 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tapo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-15 22:46:15.232 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-15 22:46:15.236 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ecowitt which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-15 22:46:15.240 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration fullykiosk which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-15 22:46:15.243 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration smartir which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-15 22:46:15.247 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-15 22:46:17.611 WARNING (MainThread) [homeassistant.config] Package centro_controllo_lavatrice_2_0 contains invalid customize
2023-06-15 22:46:53.537 WARNING (MainThread) [homeassistant.components.automation.config] The 'hide_entity' option near /config/automations.yaml:442 is deprecated, please remove it from your configuration
2023-06-15 22:46:53.785 INFO (MainThread) [custom_components.smart_irrigation]
-------------------------------------------------------------------
Smart Irrigation
Version: 0.0.78
If you have any issues with this you need to open an issue here:
https://github.com/jeroenterheerdt/HASmartIrrigation/issues
-------------------------------------------------------------------
2023-06-15 22:46:53.786 INFO (MainThread) [custom_components.smart_irrigation] Irrigation sensors: {'sensor_precipitation': 'sensor.openweathermap_rain_2', 'sensor_temperature': 'sensor.outdoor_temperature', 'sensor_min_temperature': 'sensor.temperatura_minima', 'sensor_max_temperature': 'sensor.temperatura_max', 'sensor_dewpoint': 'sensor.dewpoint', 'sensor_pressure': 'sensor.absolute_pressure', 'sensor_humidity': 'sensor.humidity', 'sensor_windspeed': 'sensor.openweathermap_wind_speed_2'}
2023-06-15 22:46:53.786 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Irrigation for smart_irrigation
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/smart_irrigation/__init__.py", line 121, in async_setup_entry
precipitation_rate = (throughput * 60) / area
~~~~~~~~~~~~~~~~^~~~~~~~
ZeroDivisionError: float division by zero

**Comment by jeroenterheerdt** [comment]
you did not specify a throughput?

**Comment by lupinve** [comment]
Hi,

Sorry what Is a throughput ?

Thanks


Il mar 20 giu 2023, 22:24 Jeroen ter Heerdt ***@***.***> ha
scritto:

**Comment by jeroenterheerdt** [comment]
when you set up the integration you filled in number of sprinklers and throughput. I think you left that 'throughput' to 0.
