### ISSUE TITLE
[Bug] V2.0 Beta6 italian language not available

### ISSUE THREAD

**Issue by apocaliss92** [jeroenterheerdt/HAsmartirrigation#153]
Hi, I'm trying to run the beta 6 but I get the following issues:
custom_components.smart_irrigation.calcmodules.localize
Source: custom_components/smart_irrigation/calcmodules/localize.py:30

Couldn't load translations language file for it

And also

Error setting up entry Smart Irrigation for smart_irrigation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 105, in async_setup_entry
    await store.set_up_factory_defaults()
  File "/config/custom_components/smart_irrigation/store.py", line 226, in set_up_factory_defaults
    await self.async_factory_default_modules()
  File "/config/custom_components/smart_irrigation/store.py", line 250, in async_factory_default_modules
    inst = m(self.hass, {})
           ^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/calcmodules/static/__init__.py", line 21, in __init__
    super().__init__(name="Static", description=localize("calcmodules.static.description",hass.config.language)+".", config=config, schema=SCHEMA)
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

Thank you very much for your awesome work!

**Comment by jeroenterheerdt** [comment]
looks like the second issue is caused by the first. Let me investigate and create a new build for this.

**Comment by jeroenterheerdt** [comment]
@apocaliss92 here it is: https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v2023.8.0-beta7, let me know if this helps! Thanks for catching this!

**Comment by apocaliss92** [comment]
The language missing one is gone but I still have this

Error setting up entry Smart Irrigation for smart_irrigation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 105, in async_setup_entry
    await store.set_up_factory_defaults()
  File "/config/custom_components/smart_irrigation/store.py", line 226, in set_up_factory_defaults
    await self.async_factory_default_modules()
  File "/config/custom_components/smart_irrigation/store.py", line 257, in async_factory_default_modules
    **{MODULE_ID: 0, MODULE_NAME: "PyETO", MODULE_DESCRIPTION:localize("calcmodules.pyeto.description",self.hass.config.language)+".",
                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
TypeError: unsupported operand type(s) for +: 'dict' and 'str'

**Comment by jeroenterheerdt** [comment]
ok, let's try that again: [v2023.8.0-beta8](https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v2023.8.0-beta8

**Comment by apocaliss92** [comment]
No errors anymore! Thanks :) just one question, will be there the possibility again to specify the sensors as before? I cannot find a way to do it

**Comment by apocaliss92** [comment]
Nevermind I just found the new wiki page, thanks again!
