### ISSUE TITLE
websocket_api script: Error executing script

### ISSUE THREAD

**Issue by andreid1303** [jeroenterheerdt/HAsmartirrigation#160]
### What happened?

Service update is not working

### How to reproduce

Call Smart Irrigation Update All

### Relevant log output

```shell
Эта ошибка возникла в пользовательской интеграции.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/smart_irrigation/__init__.py:588 
Integration: Smart Irrigation (documentation, issues) 
First occurred: 22:13:24 (2 occurrences) 
Last logged: 23:06:12

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: pop expected at most 1 argument, got 2
Traceback (most recent call last):
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/homeassistant/.homeassistant/custom_components/smart_irrigation/__init__.py", line 789, in handle_calculate_zone
    await self.async_update_zone_config(zone_id=zone_id,data=data)
  File "/var/homeassistant/.homeassistant/custom_components/smart_irrigation/__init__.py", line 588, in async_update_zone_config
    data.pop(const.ATTR_CALCULATE, None)
TypeError: pop expected at most 1 argument, got 2
```

### Which version are you running?

2023.8.0-beta12

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-057d559e436f3038853d8be3ccc738fa.json-2.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12383747/config_entry-smart_irrigation-057d559e436f3038853d8be3ccc738fa.json-2.txt)

**Comment by jeroenterheerdt** [comment]
you still have a zone with a weird key in your config. Did you _really_ uninstall / reboot / install?

**Comment by andreid1303** [comment]
beta 16 no issue
