### ISSUE TITLE
Unable to generate 'Bucket' or 'Duration' when using local sensors

### ISSUE THREAD

**Issue by dlindnegm** [jeroenterheerdt/HAsmartirrigation#175]
### What happened?

I was initiating quite a few 'Update all zones' and 'Calculate all zones' to quickly test the effect of different multiplier values.  At some point it would no longer generate any Bucket or Duration values.  I've deleted zones, re-created zones, uninstalled/restarted/reinstalled many times, but it still fails to generate bucket or durations, including with the 2 default zones generated from a fresh install.  This only happens when using my own sensors, if I use OWM it does generate both bucket and duration values.

### How to reproduce

Unsure, other than repeatedly trying different multiplier settings.

### Relevant log output

```shell
2 errors in HA logs:

First Error:

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/smart_irrigation/__init__.py:555
Integration: Smart Irrigation (documentation, issues)
First occurred: 12:56:26 AM (2 occurrences)
Last logged: 1:08:11 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/websockets.py", line 174, in post
    await coordinator.async_update_zone_config(zone, data)
  File "/config/custom_components/smart_irrigation/__init__.py", line 683, in async_update_zone_config
    await self._async_update_all()
  File "/config/custom_components/smart_irrigation/__init__.py", line 310, in _async_update_all
    sensor_values = self.build_sensor_values_for_mapping(mapping)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 555, in build_sensor_values_for_mapping
    val = float(self.hass.states.get(the_map.get(const.MAPPING_CONF_SENSOR)).state)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'unknown'

_______________________________________________________
Second Error:
This error originated from a custom integration.

Logger: custom_components.smart_irrigation
Source: custom_components/smart_irrigation/__init__.py:659
Integration: Smart Irrigation (documentation, issues)
First occurred: 12:56:41 AM (6 occurrences)
Last logged: 1:08:15 AM

Calculate for zone Default zone 1 failed: no data available.
Calculate for zone Default zone 2 failed: no data available.
```

### Which version are you running?

 v2023.8.0-beta19

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

I've confirmed that the smart_irrigation folder is removed when uninstalling.    I suspect somethings become corrupt and needs to be cleared.  But I'm not sure where the integration stores its data for which sensors to use.

Diagnostics File:
[config_entry-smart_irrigation-ae52ed84c1ec8128f421ab1e8141ebc0.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12405021/config_entry-smart_irrigation-ae52ed84c1ec8128f421ab1e8141ebc0.json.txt)

**Comment by dlindnegm** [comment]
This also occurs whether I use the Calculate all Zones or just a single zone.
