### ISSUE TITLE
BUG: during setup of integration (v0.0.16)

### ISSUE THREAD

**Issue by posixx** [jeroenterheerdt/HAsmartirrigation#19]
I added the integration from scratch; got the following errors:

Logger: custom_components.smart_irrigation.sensor
Source: custom_components/smart_irrigation/sensor.py:170

 - not enough values to unpack (expected 2, got 1)
- 'float' object has no attribute 'split'

**Comment by posixx** [comment]
sensor is reporting correct values though:

number_of_sprinklers: 7
flow: 1.12 l
throughput: 7.840000000000001 liter/minute
reference_evapotranspiration: [0.46, 0.73, 1.29, 2.09, 3.01, 3.29, 3.45, 3.02, 1.87, 1.1, 0.57, 0.42] mm
peak_evapotranspiration: 3.45 mm
area: 26.0 m2
precipitation_rate: 18.092307692307692 mm/hour
base_schedule_index_minutes: 11.44 min
unit_of_measurement: s
friendly_name: Smart Irrigation Base Schedule Index
icon: mdi:sprinkler

i will monitor if errors appear after the setup, or if this is on time only

**Comment by posixx** [comment]
To be complete: here are the complete error entries from the hass logfile:

2020-05-28 12:19:20 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Voortuin for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 296, in async_unload
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 64, in async_unload_entry
    return await hass.data[DOMAIN].async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 180, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2020-05-28 12:19:20 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Voortuin for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 217, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 59, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 163, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2020-05-28 12:19:20 ERROR (MainThread) [custom_components.smart_irrigation.sensor] not enough values to unpack (expected 2, got 1)
2020-05-28 12:19:20 ERROR (MainThread) [custom_components.smart_irrigation.sensor] not enough values to unpack (expected 2, got 1)
2020-05-28 12:19:20 ERROR (MainThread) [custom_components.smart_irrigation.sensor] not enough values to unpack (expected 2, got 1)
2020-05-28 12:19:20 ERROR (MainThread) [custom_components.smart_irrigation.sensor] not enough values to unpack (expected 2, got 1)
2020-05-28 12:19:20 ERROR (MainThread) [custom_components.smart_irrigation.sensor] not enough values to unpack (expected 2, got 1)
2020-05-28 12:19:20 ERROR (MainThread) [custom_components.smart_irrigation.sensor] 'float' object has no attribute 'split'
2020-05-28 12:19:20 ERROR (MainThread) [custom_components.smart_irrigation.sensor] 'float' object has no attribute 'split'
2020-05-28 12:19:20 ERROR (MainThread) [custom_components.smart_irrigation.sensor] 'float' object has no attribute 'split'
2020-05-28 12:19:20 ERROR (MainThread) [custom_components.smart_irrigation.sensor] not enough values to unpack (expected 2, got 1)
2020-05-28 12:19:20 ERROR (MainThread) [custom_components.smart_irrigation.sensor] 'float' object has no attribute 'split'

2020-05-28 12:57:45 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Achtertuin for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 296, in async_unload
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 64, in async_unload_entry
    return await hass.data[DOMAIN].async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 180, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2020-05-28 12:57:45 ERROR (MainThread) [custom_components.smart_irrigation.sensor] not enough values to unpack (expected 2, got 1)
2020-05-28 12:57:45 ERROR (MainThread) [custom_components.smart_irrigation.sensor] not enough values to unpack (expected 2, got 1)
2020-05-28 12:57:45 ERROR (MainThread) [custom_components.smart_irrigation.sensor] not enough values to unpack (expected 2, got 1)
2020-05-28 12:57:45 ERROR (MainThread) [custom_components.smart_irrigation.sensor] not enough values to unpack (expected 2, got 1)
2020-05-28 12:57:45 ERROR (MainThread) [custom_components.smart_irrigation.sensor] not enough values to unpack (expected 2, got 1)
2020-05-28 12:57:45 ERROR (MainThread) [custom_components.smart_irrigation.sensor] 'float' object has no attribute 'split'
2020-05-28 12:57:45 ERROR (MainThread) [custom_components.smart_irrigation.sensor] 'float' object has no attribute 'split'
2020-05-28 12:57:45 ERROR (MainThread) [custom_components.smart_irrigation.sensor] 'float' object has no attribute 'split'
2020-05-28 12:57:45 ERROR (MainThread) [custom_components.smart_irrigation.sensor] not enough values to unpack (expected 2, got 1)
2020-05-28 12:57:45 ERROR (MainThread) [custom_components.smart_irrigation.sensor] 'float' object has no attribute 'split'
2020-05-28 12:57:45 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Achtertuin for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 217, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 59, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 163, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

**Comment by posixx** [comment]
This only happens after changing options on the integration page, so it looks like updating old settings does need some extra work

**Comment by jeroenterheerdt** [comment]
Hmpf. Annoying. Closing it here if favor of the other issue
