### ISSUE TITLE
BUG: daily_adjusted_run_time sensors unavalable after HASS restart

### ISSUE THREAD

**Issue by posixx** [jeroenterheerdt/HAsmartirrigation#20]
After restart we see the following:

![image](https://user-images.githubusercontent.com/2280400/83148985-e0615f00-a0f9-11ea-90db-a9694df6812c.png)

Also logged every 5 minutes:

`2020-05-28 15:45:24 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 111, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 177, in async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 297, in async_write_ha_state
    self._async_write_ha_state()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/config/custom_components/smart_irrigation/sensor.py", line 224, in state
    self._state = self.update_state()
  File "/config/custom_components/smart_irrigation/sensor.py", line 216, in update_state
    self.coordinator.bucket
  File "/config/custom_components/smart_irrigation/sensor.py", line 481, in calculate_water_budget_and_adjusted_run_time
    if bucket_val is None or bucket_val >= 0:
TypeError: '>=' not supported between instances of 'str' and 'int'
2020-05-28 15:45:24 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 111, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 177, in async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 297, in async_write_ha_state
    self._async_write_ha_state()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/config/custom_components/smart_irrigation/sensor.py", line 224, in state
    self._state = self.update_state()
  File "/config/custom_components/smart_irrigation/sensor.py", line 216, in update_state
    self.coordinator.bucket
  File "/config/custom_components/smart_irrigation/sensor.py", line 481, in calculate_water_budget_and_adjusted_run_time
    if bucket_val is None or bucket_val >= 0:
TypeError: '>=' not supported between instances of 'str' and 'int'`

Any idea howto restore these sensors without adding the integrations again?

**Comment by posixx** [comment]
After removing the orphaned sensors and restarting HA we see:

`2020-05-28 16:14:24 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up smart_irrigation platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 446, in _async_add_entity
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 297, in async_write_ha_state
    self._async_write_ha_state()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/config/custom_components/smart_irrigation/sensor.py", line 224, in state
    self._state = self.update_state()
  File "/config/custom_components/smart_irrigation/sensor.py", line 216, in update_state
    self.coordinator.bucket
  File "/config/custom_components/smart_irrigation/sensor.py", line 481, in calculate_water_budget_and_adjusted_run_time
    if bucket_val is None or bucket_val >= 0:
TypeError: '>=' not supported between instances of 'str' and 'int'
2020-05-28 16:14:24 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up smart_irrigation platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 446, in _async_add_entity
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 297, in async_write_ha_state
    self._async_write_ha_state()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/config/custom_components/smart_irrigation/sensor.py", line 224, in state
    self._state = self.update_state()
  File "/config/custom_components/smart_irrigation/sensor.py", line 216, in update_state
    self.coordinator.bucket
  File "/config/custom_components/smart_irrigation/sensor.py", line 481, in calculate_water_budget_and_adjusted_run_time
    if bucket_val is None or bucket_val >= 0:
TypeError: '>=' not supported between instances of 'str' and 'int'`

So the daily sensors are broken

**Comment by jeroenterheerdt** [comment]
https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v0.0.18 should fix this.
