### ISSUE TITLE
Failure Calculating all automatic zones

### ISSUE THREAD

**Issue by fbloemhof** [jeroenterheerdt/HAsmartirrigation#242]
### What happened?

After installing and configuring the beta, I am unable to update the zones.

```
2023-09-06 19:17:02.976 INFO (MainThread) [custom_components.smart_irrigation] Calculating all zones
2023-09-06 19:17:02.976 INFO (MainThread) [custom_components.smart_irrigation] Calculating all automatic zones
2023-09-06 19:17:03.240 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.11/statistics.py", line 327, in _exact_ratio
return (x.numerator, x.denominator)
^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'numerator'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 94, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
result = await method(view, request, data, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/smart_irrigation/websockets.py", line 178, in post
await coordinator.async_update_zone_config(zone, data)
File "/config/custom_components/smart_irrigation/__init__.py", line 721, in async_update_zone_config
await self._async_calculate_all()
File "/config/custom_components/smart_irrigation/__init__.py", line 433, in _async_calculate_all
sensor_values = await self.apply_aggregates_to_mapping_data(mapping)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/smart_irrigation/__init__.py", line 379, in apply_aggregates_to_mapping_data
resultdata[key] = statistics.mean(d)
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/statistics.py", line 430, in mean
T, total, n = _sum(data)
^^^^^^^^^^
File "/usr/local/lib/python3.11/statistics.py", line 193, in _sum
for n, d in map(_exact_ratio, values):
File "/usr/local/lib/python3.11/statistics.py", line 330, in _exact_ratio
raise TypeError(msg)
TypeError: can't convert type 'list' to numerator/denominator
```

### How to reproduce

I have 1 zone configured:
![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8753211/217cd802-9975-4074-b390-d60e1a10f808)

And this sensorgroup:
![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8753211/968c3d8a-e886-40e3-af81-6668b650c3a2)

[config_entry-smart_irrigation-f14c5576805a213c253c5914e55c9650.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12540761/config_entry-smart_irrigation-f14c5576805a213c253c5914e55c9650.json.txt)

### Which version are you running?

 v2023.9.0-beta11

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by fbloemhof** [comment]
Okay I fixed it... I completely removed everything, restarted, reinstalled the integration and then tested the default config. That was working. Then changed the config to my own and it kept working.

I did the reinstall twice. The first time wasn't complete somehow, a part (or all) the data was still available.

I think this issue was caused after updating from v1 to v2.

**Comment by jeroenterheerdt** [comment]
changes for letting me know. Not entirely sure what happened here.
