### ISSUE TITLE
Sensors are still at 0 despite 2 days of heat

### ISSUE THREAD

**Issue by FSlunkk** [jeroenterheerdt/HAsmartirrigation#246]
### What happened?

Sensors are still at 0 despite 2 days of heat.

### How to reproduce

[config_entry-smart_irrigation-29118e7d38adc9e42a55499442423f58.json (2).txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12556651/config_entry-smart_irrigation-29118e7d38adc9e42a55499442423f58.json.2.txt)

### Which version are you running?

v2023.9.0-beta10

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
thanks - looking at this it looks like the auto calculate is never happening, because the data is still there on all your mappings. Normally if calculation has happened the weatherdata on the sensor group would be wiped. Is there anything in the logs that might tell us what happened?

**Comment by FSlunkk** [comment]
I have this :

**Comment by jeroenterheerdt** [comment]
Thank you, this is something I can investigate.

**Comment by jeroenterheerdt** [comment]
I think I have found an issue related to what you reported. Please try beta 15 and confirm if the problem is now solved.

**Comment by jlrosssc** [comment]
I had the same issue with no calculations.  Beta 15 solved it for me.

**Comment by FSlunkk** [comment]
It doesn't World for me.
Cette erreur provient d'une intégration personnalisée

Logger: aiohttp.server
Source: custom_components/smart_irrigation/__init__.py:540
Integration: Smart Irrigation (documentation, issues)
First occurred: 18:36:45 (2 occurrences)
Last logged: 18:36:51

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/websockets.py", line 181, in post
    await coordinator.async_update_zone_config(zone, data)
  File "/config/custom_components/smart_irrigation/__init__.py", line 736, in async_update_zone_config
    data = self.calculate_module(res, weatherdata=sensor_values, forecastdata=forecastdata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 540, in calculate_module
    explanation += ".<br/>"+localize("module.calculation.explanation.maximum-bucket-is", self.hass.config.language)+" {}".format(round(float(zone.get(const.ZONE_MAXIMUM_BUCKET)),1))
                   ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "dict") to str

**Comment by FSlunkk** [comment]
[config_entry-smart_irrigation-29118e7d38adc9e42a55499442423f58.json (5).txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12580027/config_entry-smart_irrigation-29118e7d38adc9e42a55499442423f58.json.5.txt)

**Comment by jeroenterheerdt** [comment]
Found a bug. It has to do with the French translation missing some strings and the logic for falling back to English not working. Will fix in next beta.

**Comment by FSlunkk** [comment]
Thanks, beta 16 fixes the bug.
