### ISSUE TITLE
daily sensors not updated?

### ISSUE THREAD

**Issue by posixx** [jeroenterheerdt/HAsmartirrigation#25]
Ok i have re-added the integrations after v0.0.20. This was around 22 hours i think. At 23h the daily sensor should update right?

![image](https://user-images.githubusercontent.com/2280400/83195692-ed527280-a13a-11ea-876d-d57f59801eaf.png)

But they stay at 0. Do i need to wait a day for these to get updated? Or is this a bug/issue..

**Comment by jeroenterheerdt** [comment]
is auto refresh enabled?

**Comment by posixx** [comment]
Yes and the time is on 23:00
________________________________

**Comment by jeroenterheerdt** [comment]
found the bug, will release v0.0.21 soon. please test that and confirm/close.

**Comment by posixx** [comment]
Nope doesn't work. 

2020-05-29 23:00:00 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/smart_irrigation/__init__.py", line 327, in _async_update_last_of_day
    self._update_last_of_day()
  File "/config/custom_components/smart_irrigation/__init__.py", line 316, in _update_last_of_day
    self.bucket = self.bucket + bucket_delta
TypeError: can only concatenate str (not "float") to str
2020-05-29 23:00:00 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/smart_irrigation/__init__.py", line 327, in _async_update_last_of_day
    self._update_last_of_day()
  File "/config/custom_components/smart_irrigation/__init__.py", line 316, in _update_last_of_day
    self.bucket = self.bucket + bucket_delta
TypeError: can only concatenate str (not "float") to str

**Comment by posixx** [comment]
It is and was 0:

![image](https://user-images.githubusercontent.com/2280400/83305735-982d6400-a201-11ea-991f-9107b858b7a0.png)

**Comment by jeroenterheerdt** [comment]
ok, one more screenshot: can you share the value of netto precipitation as well?

**Comment by posixx** [comment]
daily sensors:

![image](https://user-images.githubusercontent.com/2280400/83306207-6f599e80-a202-11ea-8784-e95823910fbf.png)

base sensors:

![image](https://user-images.githubusercontent.com/2280400/83306239-7ed8e780-a202-11ea-884e-9268e270a6d1.png)

**Comment by jeroenterheerdt** [comment]
not sure what is going on here, I will be providing you a new version that has more logging. You should see an `INFO` entry in the log saying: "Updating bucket [value] with netto_precipitation: [value]". Can you provide me with that once you've seen it?

**Comment by posixx** [comment]
no problem, can i trigger manually? Of do i have to wait about 24hr

**Comment by jeroenterheerdt** [comment]
you can trigger it manually.

**Comment by jeroenterheerdt** [comment]
please test using v0.0.22

**Comment by posixx** [comment]
Ok,, as the sensor names are changed, should i remove integrations, reboot and re-add? It;s 1 AM here now so will do this tomorrow.

**Comment by jeroenterheerdt** [comment]
I would remove, readd. that should take care of it. oh and go to sleep :)

**Comment by posixx** [comment]
Ok implemented new version. Now when calling smart_irrigation.voortuin_calculate_daily_adjusted_run_time it works:

![image](https://user-images.githubusercontent.com/2280400/83326520-02332100-a275-11ea-9968-7ddc675d9561.png)

Calling smart_irrigation.voortuin_reset_bucket resets the daily values. So this looks good!

From the core log:

2020-05-30 12:54:00 INFO (MainThread) [custom_components.smart_irrigation] Calculate Daily Adjusted Run Time service called, calculating now.
2020-05-30 12:54:00 INFO (MainThread) [custom_components.smart_irrigation] Updating bucket: 0.0 with netto_precipitation: -8.770122066475068
2020-05-30 12:54:22 INFO (MainThread) [custom_components.smart_irrigation] Updating Smart Irrigation Data
2020-05-30 12:54:22 INFO (MainThread) [custom_components.smart_irrigation] Updating Smart Irrigation Data
2020-05-30 12:54:22 INFO (MainThread) [custom_components.smart_irrigation.sensor] rain: 0.0, snow: 0.0
2020-05-30 12:54:22 INFO (MainThread) [custom_components.smart_irrigation.sensor] rain: 0.0, snow: 0.0
2020-05-30 12:54:22 INFO (MainThread) [custom_components.smart_irrigation.sensor] rain: 0.0, snow: 0.0
2020-05-30 12:54:22 INFO (MainThread) [custom_components.smart_irrigation.sensor] rain: 0.0, snow: 0.0
2020-05-30 12:55:02 INFO (SyncWorker_18) [custom_components.smart_irrigation] Reset bucket service called, resetting bucket to 0.

Let's see if it also works tonight at 23:00

**Comment by posixx** [comment]
Also on 23h it worked last night. So solved!

**Comment by jeroenterheerdt** [comment]
Thanks!
