### ISSUE TITLE
hourly sensor unavailable

### ISSUE THREAD

**Issue by ciechompl** [jeroenterheerdt/HAsmartirrigation#26]
v. 0.0.22
removed integration, removed component, restart, added component, restart, added integration ->
hourly sensor unavailable:

![image](https://user-images.githubusercontent.com/27088154/83326816-33145580-a277-11ea-9d62-cb85f8935bbb.png)

log:
```
2020-05-30 13:10:17 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up smart_irrigation platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 446, in _async_add_entity
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 297, in async_write_ha_state
    self._async_write_ha_state()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/config/custom_components/smart_irrigation/sensor.py", line 308, in state
    self._state = self.update_state()
  File "/config/custom_components/smart_irrigation/sensor.py", line 286, in update_state
    self.precipitation = self.get_precipitation(data)
  File "/config/custom_components/smart_irrigation/sensor.py", line 410, in get_precipitation
    retval = self.rain + self.snow
TypeError: unsupported operand type(s) for +: 'float' and 'str'
```

**Comment by posixx** [comment]
Ok, so you didn;t rename your integration.. Can you set your own integration name during setup (first popup above the OWM Api key). I'm using v0.0.22 using 2 integrations and didn't see this problem at all.

**Comment by ciechompl** [comment]
i do not have to rename it as default name is perfectly fine for me :)  further, all my other template sensors are ready for default name so do want to do it :) 
anyway ... it is strange that only hourly sensor is unavailable , daily and base are ok

**Comment by ciechompl** [comment]
but for test purposes I added second integration with some new name and all works ok. So must be issue with default name used during first setup

**Comment by jeroenterheerdt** [comment]
Huh? I am using the default name in my production setup and it works fine. Please don't change anything. I will add some debug logging.

**Comment by jeroenterheerdt** [comment]
In the meantime can you please share screenshots of all details so I can replicate your situation here?

**Comment by ciechompl** [comment]
funny but when I added second integration with some new name and removed it from integration list, without even touching the original one where I had broken sensor , everything is ok now .. .so really strange :) I have not done anything despite adding second integration and removing it .. .that's all  .. I haven't even restarted HA :)

**Comment by jeroenterheerdt** [comment]
Weird. Without knowledge of the data at the time I cannot fix this. I will build some extra safeguards for what I think is going on though.

**Comment by ciechompl** [comment]
indeed weird :) what kind of data/screenshots shall I collect next time ?

**Comment by jeroenterheerdt** [comment]
The screenshots that you shared: entities and their attributes are enough

**Comment by ciechompl** [comment]
you will not gonna believe :) just restarted HA and again my hourly sensor unavailable

screenshots: 
![image](https://user-images.githubusercontent.com/27088154/83334804-4cce9080-a2a9-11ea-9df8-9c586a87e2aa.png)

![image](https://user-images.githubusercontent.com/27088154/83334812-548e3500-a2a9-11ea-84da-3ab3b32e179d.png)

![image](https://user-images.githubusercontent.com/27088154/83334819-5ce67000-a2a9-11ea-80aa-ecbd4f58c4c2.png)

log: 
```
2020-05-30 19:09:17 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 111, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 177, in async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 297, in async_write_ha_state
    self._async_write_ha_state()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/config/custom_components/smart_irrigation/sensor.py", line 308, in state
    self._state = self.update_state()
  File "/config/custom_components/smart_irrigation/sensor.py", line 286, in update_state
    self.precipitation = self.get_precipitation(data)
  File "/config/custom_components/smart_irrigation/sensor.py", line 410, in get_precipitation
    retval = self.rain + self.snow
TypeError: unsupported operand type(s) for +: 'float' and 'str'
```

**Comment by jeroenterheerdt** [comment]
thanks, stay tuned for an update soonish ;)

**Comment by ciechompl** [comment]
no rush :) ... raining second day in a row and tomorrow seem to be the same so zero stress :)

**Comment by jeroenterheerdt** [comment]
;)

**Comment by ciechompl** [comment]
update to .23 , HA restart nad hourly sensor works :) ... even without full component reinstall ... thx

**Comment by jeroenterheerdt** [comment]
Please give in another day and if it still works go ahead and close the issue

**Comment by ciechompl** [comment]
so far so good :) closing

**Comment by jeroenterheerdt** [comment]
Thanks!
