### ISSUE TITLE
Error while resetting bucket

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#272]
### What happened?

After successfully resetting a bucket an error occurs in the logs.

### How to reproduce

Call service smart_irrigation.reset_bucket

### Relevant log output

```shell
Logger: homeassistant.components.automation.bewasserung_wohnzimmer
Source: helpers/event.py:1578
Integration: Automation (documentation, issues)
First occurred: 09:01:47 (2 occurrences)
Last logged: 09:01:47

Bewässerung Wohnzimmer: Error executing script. Unexpected error for call_service at pos 7:
While executing automation automation.bewasserung_wohnzimmer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1969, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2006, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 1046, in handle_reset_bucket
    await self.async_update_zone_config(zone_id=zone_id,data=data)
  File "/config/custom_components/smart_irrigation/__init__.py", line 900, in async_update_zone_config
    self.register_start_event()
  File "/config/custom_components/smart_irrigation/__init__.py", line 913, in register_start_event
    self._track_sunrise_event_unsub()
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1578, in async_detach
    assert self._unsub_sun is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

### Which version are you running?

v2023.9.0-beta21

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by dlindnegm** [comment]
I have this same error on beta21.  I call the reset all buckets service at 10:00 am after all watering is complete.  It appears to have reset the buckets in the GUI.  I can try enabling debug logging tomorrow to grab log file after it happens.

**Comment by gatonero** [comment]
> enabling debug logging

I enabled debug logging but no error there. The only items I see is the event when I started smart_irrigation.reset_bucket manually at 09:58 and registering the zones.

```
2023-09-20 09:58:13.875 DEBUG (MainThread) [custom_components.smart_irrigation] calling register start event from init
2023-09-20 09:58:18.274 DEBUG (MainThread) [custom_components.smart_irrigation.sensor] sensor.smart_irrigation_bewasserung_wohnzimmer is added to hass
2023-09-20 09:58:18.276 DEBUG (MainThread) [custom_components.smart_irrigation.sensor] sensor.smart_irrigation_bewasserung_terrasse is added to hass
2023-09-20 09:58:18.279 DEBUG (MainThread) [custom_components.smart_irrigation.sensor] sensor.smart_irrigation_bewasserung_kuche is added to hass
2023-09-20 09:58:18.282 DEBUG (MainThread) [custom_components.smart_irrigation.sensor] sensor.smart_irrigation_atest is added to hass
```

**Comment by mauritsivs** [comment]
same here, pressing reset all buckets in the UI does nothing, gives error in log:
```
Logger: aiohttp.server
Source: helpers/event.py:1578
First occurred: 10:09:32 PM (2 occurrences)
Last logged: 10:10:17 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/websockets.py", line 185, in post
    await coordinator.async_update_zone_config(zone, data)
  File "/config/custom_components/smart_irrigation/__init__.py", line 900, in async_update_zone_config
    self.register_start_event()
  File "/config/custom_components/smart_irrigation/__init__.py", line 913, in register_start_event
    self._track_sunrise_event_unsub()
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1578, in async_detach
    assert self._unsub_sun is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by gatonero** [comment]
This error didn't appear with beta22 anymore! :-)
