### ISSUE TITLE
Calculate Button doesn't calculate, but produces error in logg

### ISSUE THREAD

**Issue by w1Ngx** [jeroenterheerdt/HAsmartirrigation#294]
### What happened?

I configured a fresh V2 install according to the installation guide.
After trying to calculcate my zone, it still shows "-" and I get an error in system error log.

### How to reproduce

Click on calculate.

### Relevant log output

```shell
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/smart_irrigation/calcmodules/pyeto/__init__.py:78
Integration: Smart Irrigation (documentation, issues)
First occurred: 7:15:29 AM (9 occurrences)
Last logged: 8:35:57 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/websockets.py", line 185, in post
    await coordinator.async_update_zone_config(zone, data)
  File "/config/custom_components/smart_irrigation/__init__.py", line 813, in async_update_zone_config
    await self._async_calculate_all()
  File "/config/custom_components/smart_irrigation/__init__.py", line 519, in _async_calculate_all
    data = self.calculate_module(zone, weatherdata=sensor_values,forecastdata=forecastdata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 578, in calculate_module
    delta = modinst.calculate(weather_data=weatherdata, forecast_data = forecastdata)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/calcmodules/pyeto/__init__.py", line 78, in calculate
    deltas.append(self.calculate_et_for_day(forecast_data[x]))
                                            ~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

### Which version are you running?

V2023.9.2

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-3449ac96973de5ce532ac215b3e02eb6.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12723706/config_entry-smart_irrigation-3449ac96973de5ce532ac215b3e02eb6.json.txt)

**Comment by jeroenterheerdt** [comment]
will be fixed in next release.
