### ISSUE TITLE
executing reset_all_buckets service in V2 throws error

### ISSUE THREAD

**Issue by kayserjan** [jeroenterheerdt/HAsmartirrigation#297]
### What happened?

Reset_all_buckets srvice throws and error both on UI and in LOGS (pasted)

[config_entry-smart_irrigation-0ccbefbed592d9fabbc576155498cb32.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12737736/config_entry-smart_irrigation-0ccbefbed592d9fabbc576155498cb32.json.txt)

### How to reproduce

1. IN HA go to Developer Tools>Services>
2. pick service "Smart Irrigation: reset_all_buckets"
3. Click EXECUTE
4. Error comes up "Cannot execute smart_irrigation.reset_all_buckets. Unknown error"

### Relevant log output

```shell
Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/event.py:1578
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:43:09 (12 occurrences)
Last logged: 12:46:27

[546481490496]
[545702408512]
[545734356544] Error handling message: Unknown error (unknown_error) Jan from 80.253.213.7 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36)
[545734360000]
[545734360000] Error handling message: Unknown error (unknown_error) Jan from 80.253.213.7 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 227, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1969, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2006, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 1072, in handle_reset_all_buckets
    await self._async_set_all_buckets(0)
  File "/config/custom_components/smart_irrigation/__init__.py", line 1008, in _async_set_all_buckets
    await self.async_update_zone_config(zone_id=zone.get(const.ZONE_ID),data=data)
  File "/config/custom_components/smart_irrigation/__init__.py", line 907, in async_update_zone_config
    self.register_start_event()
  File "/config/custom_components/smart_irrigation/__init__.py", line 920, in register_start_event
    self._track_sunrise_event_unsub()
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1578, in async_detach
    assert self._unsub_sun is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

### Which version are you running?

HA 2023.9.3  Smart Irrigation v2023.9.2

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
Thanks for reporting!

**Comment by GiorgioUghini** [comment]
It happens also with UPDATE and CALCULATE services as well. Here's step to reproduce:
- IN HA go to Developer Tools>Services>
- Pick service "Smart Irrigation: update_zone" and select the zone
- OR
- Pick service "Smart Irrigation: calculate_zone" and select the zone
- Click EXECUTE
- Error comes up "Cannot execute smart_irrigation.reset_all_buckets. Unknown error"

And here's the logs (similar to yours):

```
2023-09-28 18:05:51.104 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140301496902976] Error handling message: Unknown error (unknown_error) Giorgio from 10.8.0.3 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.43)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 716, in handle_execute_script
    response = await script_obj.async_run(msg.get("variables"), context=context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1569, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 420, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 470, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 493, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 1028, in handle_calculate_zone
    await self.async_update_zone_config(zone_id=zone_id,data=data)
  File "/config/custom_components/smart_irrigation/__init__.py", line 907, in async_update_zone_config
    self.register_start_event()
  File "/config/custom_components/smart_irrigation/__init__.py", line 920, in register_start_event
    self._track_sunrise_event_unsub()
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1547, in async_detach
    assert self._unsub_sun is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by apocaliss92** [comment]
Hey! Same here on .4
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1969, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2006, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 1079, in handle_reset_all_buckets
    await self._async_set_all_buckets(0)
  File "/config/custom_components/smart_irrigation/__init__.py", line 1015, in _async_set_all_buckets
    await self.async_update_zone_config(zone_id=zone.get(const.ZONE_ID),data=data)
  File "/config/custom_components/smart_irrigation/__init__.py", line 914, in async_update_zone_config
    self.register_start_event()
  File "/config/custom_components/smart_irrigation/__init__.py", line 927, in register_start_event
    self._track_sunrise_event_unsub()
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1578, in async_detach
    assert self._unsub_sun is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by dlindnegm** [comment]
I have the same issue with v2023.9.2 when trying to reset all buckets.  I've noticed that only the bucket for the first zone is reset to zero, and the error occurs and none of the remaining zones are reset.

**Comment by dziadzi123** [comment]
Same here

**Comment by GiorgioUghini** [comment]
Not sure https://github.com/jeroenterheerdt/HAsmartirrigation/commit/eaa251940b891311248a8786c78a8ccf5189c9d9 solves this. The error on update_all_zone service call is gone, but I have this very same errors on: update_zone, calculate_zone, and calculate_all_zones.

At least not for me (same as before).
![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/23707134/12886142-f1d9-4b79-a57b-385cac7ec800)

**Comment by GiorgioUghini** [comment]
Error is finally gone in all service calls except "update_zone", where it is still present.

**Comment by jeroenterheerdt** [comment]
> Error is finally gone in all service calls except "update_zone", where it is still present.

not sure what method it is in. I am not seeing this on my end, can you share logs?

**Comment by GiorgioUghini** [comment]
The logs are the same, with the error `assert self._unsub_sun is not None` as before...
This is the service 
![Screenshot_2023-10-10-06-19-24-79_c3a231c25ed346e59462e84656a70e50](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/23707134/8fa4a8ae-536c-4130-8624-41d36c4ef06f)

**Comment by gatonero** [comment]
This doesn't happen anymore in v2023.9.3-beta-4

**Comment by gatonero** [comment]
I can reproduce  this failure in v2023.9.3-beta-4.

**Comment by gatonero** [comment]
It throws two errors:

`Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:468
First occurred: 11:50:35 (3 occurrences)
Last logged: 16:27:29

websocket_api script: Error executing script. Unexpected error for call_service at pos 1:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 1078, in handle_update_zone
    await self.async_update_zone_config(zone_id=zone_id,data=data)
  File "/config/custom_components/smart_irrigation/__init__.py", line 937, in async_update_zone_config
    self.register_start_event()
  File "/config/custom_components/smart_irrigation/__init__.py", line 950, in register_start_event
    self._track_sunrise_event_unsub()
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1558, in async_detach
    assert self._unsub_sun is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
`

`Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/event.py:1558
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:50:35 (3 occurrences)
Last logged: 16:27:29

[140261405779520] Error handling message: Unknown error (unknown_error) Christoph from 37.201.98.71 (Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0)
[140261532257984] Error handling message: Unknown error (unknown_error) Christoph from 37.201.98.71 (Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 727, in handle_execute_script
    script_result = await script_obj.async_run(msg.get("variables"), context=context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1578, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 420, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 470, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 493, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 1078, in handle_update_zone
    await self.async_update_zone_config(zone_id=zone_id,data=data)
  File "/config/custom_components/smart_irrigation/__init__.py", line 937, in async_update_zone_config
    self.register_start_event()
  File "/config/custom_components/smart_irrigation/__init__.py", line 950, in register_start_event
    self._track_sunrise_event_unsub()
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1558, in async_detach
    assert self._unsub_sun is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
`

**Comment by jeroenterheerdt** [comment]
let's try this once more - does beta5 solve this finally?

**Comment by GiorgioUghini** [comment]
IT SEEMS that all services are working now 😃 thank you!!

**Comment by jeroenterheerdt** [comment]
ok great, let's wait for @gatonero to confirm and then we can call this done.

**Comment by gatonero** [comment]
A little late but I confirm ;-)
