### ISSUE TITLE
Smart Irrigation, Space, No devices or entities, Failed to set up

### ISSUE THREAD

**Issue by raul811** [jeroenterheerdt/HAsmartirrigation#326]
### What happened?

After the last update the integration is still not working

### How to reproduce

I uninstall everything from the old version. And after that I installed the new version and still not working.

### Relevant log output

```shell
Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 11:52:32 (1 occurrences)
Last logged: 11:52:32

Error setting up entry Smart Irrigation for smart_irrigation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 64, in async_setup_entry
    store = await async_get_registry(hass)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/store.py", line 561, in async_get_registry
    return cast(SmartIrrigationStorage, await task)
                                        ^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/store.py", line 556, in _load_reg
    await registry.async_load()
  File "/config/custom_components/smart_irrigation/store.py", line 228, in async_load
    inst = m(self.hass, modconfig)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/calcmodules/static/__init__.py", line 21, in __init__
    super().__init__(name="Static", description=localize("calcmodules.static.description",hass.config.language)+".", config=config, schema=SCHEMA)
  File "/config/custom_components/smart_irrigation/calcmodules/calcmodule.py", line 26, in __init__
    raise e
  File "/config/custom_components/smart_irrigation/calcmodules/calcmodule.py", line 24, in __init__
    self._schema(config)
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected float for dictionary value @ data['delta']
```

### Which version are you running?

v2024.1.0, button

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

Sorry but I don't have a diagnostic file on integration

**Comment by jeroenterheerdt** [comment]
Please remove, make sure everything related to this integration is gone from the hidden storage folder (`.storage`) and reinstall.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by raul811** [comment]
After I delete the smart irrigation from heights. Store everything it's working, thank you.

**Comment by jeroenterheerdt** [comment]
yeah, sometimes stuff gets stuck there...
