### ISSUE TITLE
Failed to set up (see the logs)

### ISSUE THREAD

**Issue by Petache1** [jeroenterheerdt/HAsmartirrigation#353]
### What happened?

I installed the integration a couple of weeks ago and it works fine so far. 
after homeassistant update yesterday, it stop working and shows error messages. 

Restart, uninstall and installing, downgrade, update do not help. 

Core 2024.4.4
Supervisor 2024.04.0
Operating System 12.2
Frontend 20240403.1

### How to reproduce

update hass io and core 

### Relevant log output

```shell
Protokolldetails (FEHLER)
Logger: homeassistant.config_entries
Quelle: config_entries.py:551
Erstmals aufgetreten: 08:49:09 (1 Vorkommnisse)
Zuletzt protokolliert: 08:49:09

Error setting up entry Smart Irrigation for smart_irrigation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 72, in async_setup_entry
    store = await async_get_registry(hass)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/store.py", line 645, in async_get_registry
    return cast(SmartIrrigationStorage, await task)
                                        ^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/store.py", line 640, in _load_reg
    await registry.async_load()
  File "/config/custom_components/smart_irrigation/store.py", line 269, in async_load
    inst = m(self.hass, modconfig)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/calcmodules/static/__init__.py", line 21, in __init__
    super().__init__(name="Static", description=localize("calcmodules.static.description",hass.config.language)+".", config=config, schema=SCHEMA)
  File "/config/custom_components/smart_irrigation/calcmodules/calcmodule.py", line 26, in __init__
    raise e
  File "/config/custom_components/smart_irrigation/calcmodules/calcmodule.py", line 24, in __init__
    self._schema(config)
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected float for dictionary value @ data['delta']

__________________________________________________________________________________
Protokolldetails (WARNUNG)
Logger: homeassistant.components.frontend
Quelle: components/frontend/__init__.py:319
Integration: Home Assistant Frontend (Dokumentation, Probleme)
Erstmals aufgetreten: 08:50:45 (1 Vorkommnisse)
Zuletzt protokolliert: 08:50:45

Removing unknown panel smart_irrigation

_________________________________________________________________________
Protokolldetails (FEHLER)
Logger: homeassistant.config_entries
Quelle: config_entries.py:551
Erstmals aufgetreten: 08:51:22 (1 Vorkommnisse)
Zuletzt protokolliert: 08:51:22

Error setting up entry Smart Irrigation for smart_irrigation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 72, in async_setup_entry
    store = await async_get_registry(hass)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/store.py", line 645, in async_get_registry
    return cast(SmartIrrigationStorage, await task)
                                        ^^^^^^^^^^
voluptuous.error.MultipleInvalid: expected float for dictionary value @ data['delta']
```

### Which version are you running?

2024.4.3

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

-

**Comment by jeroenterheerdt** [comment]
Duplicate of https://github.com/jeroenterheerdt/HAsmartirrigation/issues/341. Seems only to happen on German systems?

**Comment by Petache1** [comment]
The solution mentioned in https://github.com/jeroenterheerdt/HAsmartirrigation/issues/341 works for me too. Thank you.
