### ISSUE TITLE
host='api.openweathermap.org' Read timed out - and the integration has failed to calculate

### ISSUE THREAD

**Issue by akcasoy** [jeroenterheerdt/HAsmartirrigation#382]
### What happened?

I have realized that the calculation could not been done for the first time. A manual calculation after a few minutes on the zone section of the integration was successful.
I do not know if this was a timeout of the openweathermap API, of if we simply need a longer timeout than 60.

### How to reproduce

This is the first system log warning:
<img width="695" alt="Bildschirmfoto 2024-05-26 um 23 30 10" src="https://github.com/jeroenterheerdt/HAsmartirrigation/assets/12121451/98c78760-d8d9-4a4e-89cd-5a03e7d3b48c">

And it ended up with this error:

```
This error originated from a custom integration.
Logger: homeassistant
Source: custom_components/smart_irrigation/OWMClient.py:73
integration: Smart Irrigation (documentation, issues)
First occurred: 11:01:00 PM (1 occurrences)
Last logged: 11:01:00 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1423, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 707, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1252, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1104, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 469, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 358, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.openweathermap.org', port=443): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/smart_irrigation/__init__.py", line 659, in _async_calculate_all
    forecastdata = await self.hass.async_add_executor_job(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/OWMClient.py", line 157, in get_forecast_data
    raise ex
  File "/config/custom_components/smart_irrigation/OWMClient.py", line 73, in get_forecast_data
    req = requests.get(self.url,timeout=60) #60 seconds timeout
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.openweathermap.org', port=443): Read timed out. (read timeout=60)

```

### Which version are you running?

v2024.4.3

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
Most likely an outage of owm or your internet connection. Apart from nicer handling nothing we can do about that.

**Comment by akcasoy** [comment]
Can we at least make a retry? i.e. a few minutes later... and again a few minutes later..
We do have in our software systems for those cases mostly 3 retries.

**Comment by jeroenterheerdt** [comment]
Sure we can, feel free to implement it. First time this has happened in forever, so not high on my list to fix.

**Comment by volkov-d** [comment]
I had exactly the same issue yesterday. v2024.4.3

**Comment by jeroenterheerdt** [comment]
should be fixed in latest beta
