### ISSUE TITLE
Integration won't calculate since May 25th.

### ISSUE THREAD

**Issue by omenek159** [jeroenterheerdt/HAsmartirrigation#386]
### What happened?

Since May 25th integration won't calculate. Log shows error about asynchronous function, but if I add 'await' in line 1142 then it will throw another error: 

> TypeError: PyETO.__init__() missing 1 required positional argument: 'description'#033[0m

[config_entry-smart_irrigation-5ae2f4e6574b1aa4c1258f4d54c0bc05.json](https://github.com/user-attachments/files/15522303/config_entry-smart_irrigation-5ae2f4e6574b1aa4c1258f4d54c0bc05.json)

### How to reproduce

Just click Calculate.

### Relevant log output

```shell
Jun  1 17:08:42 homeassistant homeassistant[315246] #033[31m2024-06-01 17:08:41.760 ERROR (MainThread) [aiohttp.server] Error handling request
Jun  1 17:08:42 homeassistant homeassistant[315246] Traceback (most recent call last):
Jun  1 17:08:42 homeassistant homeassistant[315246]  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
Jun  1 17:08:42 homeassistant homeassistant[315246]    resp = await request_handler(request)
Jun  1 17:08:42 homeassistant homeassistant[315246]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun  1 17:08:42 homeassistant homeassistant[315246]  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
Jun  1 17:08:42 homeassistant homeassistant[315246]    resp = await handler(request)
Jun  1 17:08:42 homeassistant homeassistant[315246]           ^^^^^^^^^^^^^^^^^^^^^^
Jun  1 17:08:42 homeassistant homeassistant[315246]  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
Jun  1 17:08:42 homeassistant homeassistant[315246]    return await handler(request)
Jun  1 17:08:42 homeassistant homeassistant[315246]           ^^^^^^^^^^^^^^^^^^^^^^
Jun  1 17:08:42 homeassistant homeassistant[315246]  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
Jun  1 17:08:42 homeassistant homeassistant[315246]    return await handler(request)
Jun  1 17:08:42 homeassistant homeassistant[315246]           ^^^^^^^^^^^^^^^^^^^^^^
Jun  1 17:08:42 homeassistant homeassistant[315246]  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
Jun  1 17:08:42 homeassistant homeassistant[315246]    return await handler(request)
Jun  1 17:08:42 homeassistant homeassistant[315246]           ^^^^^^^^^^^^^^^^^^^^^^
Jun  1 17:08:42 homeassistant homeassistant[315246]  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
Jun  1 17:08:42 homeassistant homeassistant[315246]    return await handler(request)
Jun  1 17:08:42 homeassistant homeassistant[315246]           ^^^^^^^^^^^^^^^^^^^^^^
Jun  1 17:08:42 homeassistant homeassistant[315246]  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 88, in ban_middleware
Jun  1 17:08:42 homeassistant homeassistant[315246]    return await handler(request)
Jun  1 17:08:42 homeassistant homeassistant[315246]           ^^^^^^^^^^^^^^^^^^^^^^
Jun  1 17:08:42 homeassistant homeassistant[315246]  File "/usr/local/lib/python3.12/site-packages/aiohttp_session/__init__.py", line 199, in factory
Jun  1 17:08:42 homeassistant homeassistant[315246]    response = await handler(request)
Jun  1 17:08:42 homeassistant homeassistant[315246]               ^^^^^^^^^^^^^^^^^^^^^^
Jun  1 17:08:42 homeassistant homeassistant[315246]  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 295, in auth_middleware
Jun  1 17:08:42 homeassistant homeassistant[315246]    return await handler(request)
Jun  1 17:08:42 homeassistant homeassistant[315246]           ^^^^^^^^^^^^^^^^^^^^^^
Jun  1 17:08:42 homeassistant homeassistant[315246]  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
Jun  1 17:08:42 homeassistant homeassistant[315246]    response = await handler(request)
Jun  1 17:08:42 homeassistant homeassistant[315246]               ^^^^^^^^^^^^^^^^^^^^^^
Jun  1 17:08:42 homeassistant homeassistant[315246]  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
Jun  1 17:08:42 homeassistant homeassistant[315246]    result = await handler(request, **request.match_info)
Jun  1 17:08:42 homeassistant homeassistant[315246]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun  1 17:08:42 homeassistant homeassistant[315246]  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
Jun  1 17:08:42 homeassistant homeassistant[315246]    return await method(view, request, data, *args, **kwargs)
Jun  1 17:08:42 homeassistant homeassistant[315246]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun  1 17:08:42 homeassistant homeassistant[315246]  File "/config/custom_components/smart_irrigation/websockets.py", line 197, in post
Jun  1 17:08:42 homeassistant homeassistant[315246]    await coordinator.async_update_zone_config(zone, data)
Jun  1 17:08:42 homeassistant homeassistant[315246]  File "/config/custom_components/smart_irrigation/__init__.py", line 1205, in async_update_zone_config
Jun  1 17:08:42 homeassistant homeassistant[315246]    await self._async_calculate_all()
Jun  1 17:08:42 homeassistant homeassistant[315246]  File "/config/custom_components/smart_irrigation/__init__.py", line 658, in _async_calculate_all
Jun  1 17:08:42 homeassistant homeassistant[315246]    if modinst and modinst.name == "PyETO" and modinst._forecast_days > 0:
Jun  1 17:08:42 homeassistant homeassistant[315246]                   ^^^^^^^^^^^^
Jun  1 17:08:42 homeassistant homeassistant[315246] AttributeError: 'coroutine' object has no attribute 'name'#033[0m


Jun  1 17:08:42 homeassistant homeassistant[315246] #033[33m2024-06-01 17:08:41.763 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:466: RuntimeWarning: coroutine 'SmartIrrigationCoordinator.getModuleInstanceByID' was never awaited
Jun  1 17:08:42 homeassistant homeassistant[315246]  reset = await self.finish_response(request, resp, start_time)
```

### Which version are you running?

2024.5.3

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
Huh, that's weird. I am not seeing that here... I'll recheck.

**Comment by nybodha** [comment]
I have the same problem, last calculation 29 of May.

**Comment by jeroenterheerdt** [comment]
please install 2024.6.0 and verify this was fixed.

**Comment by omenek159** [comment]
Bucket is calculating now, but it won't update ui because of localization. Looks like fallback to en doesn't work in this case. 

[si_log.txt](https://github.com/user-attachments/files/15542730/si_log.txt)

**Comment by jeroenterheerdt** [comment]
Weird, it worked fine in my tests but I am on English. I will check it again. Sorry for the inconvenience

**Comment by omenek159** [comment]
I solved it by modifying 
localize.py:19
`if language in SUPPORTED_LANGUAGES:`
and localize.py:30
```
# fallback to english in case string wasn't found
# if language == "en" or not isinstance(translated_string, str):
    else:
        language = "en"
```

in root dir and /calcmodules/

**Comment by nybodha** [comment]
I install the latest and in settings service and service it shows the previous in the app. 

Still got this error
async_update_zone_config
    await self._async_calculate_all()
  File "/config/custom_components/smart_irrigation/__init__.py", line 688, in _async_calculate_all
    self.store.async_update_zone(zone.get(const.ZONE_ID), data)
  File "/config/custom_components/smart_irrigation/store.py", line 505, in async_update_zone
    if ATTR_NEW_MULTIPLIER_VALUE in changes:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'coroutine' is not iterable
2024-06-04 07:29:34.844 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:466: RuntimeWarning: coroutine 'SmartIrrigationCoordinator.calculate_module' was never awaited
  reset = await self.finish_response(request, resp, start_time)

**Comment by omenek159** [comment]
@nybodha #388

**Comment by jeroenterheerdt** [comment]
@omenek159 what language are you on? I am struggling to reproduce this issue unfortunately.

**Comment by jeroenterheerdt** [comment]
should be fixed in next beta release

**Comment by omenek159** [comment]
Yeah, I can confirm that everything is working as expected now :)

**Comment by nybodha** [comment]
Yes, just install and without checked the log files it looks very good. Start up and when I press calculate all i got - 1.1 in the bucket. 
Great nightly work 🌞

**Comment by jeroenterheerdt** [comment]
The benefit of timezones... For me it was the end of the day 😂. Tomorrow end of day I'll wrap up the official release and then it's on to big things to fix the biggest problem with this integration: the sampling of sensors is not enough for places that have big changes in weather in a day. Anyway thats for tomorrow and the days after. First need to give my other integrations some love. Oh, and getting some sleep...
