### ISSUE TITLE
Konfiguration Problem

### ISSUE THREAD

**Issue by bmause** [jeroenterheerdt/HAsmartirrigation#390]
### What happened?

Can't create a configuration

### How to reproduce

I have tried to delete and reinstall Eschen several times, every time after the api input from openweather this message comes.

### Relevant log output

```shell
Logger: homeassistant.config_entries
Quelle: config_entries.py:584
Erstmals aufgetreten: 19:42:18 (1 Vorkommnisse)
Zuletzt protokolliert: 19:42:18

Error setting up entry Smart Irrigation for smart_irrigation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 584, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 63, in async_setup_entry
    store = await async_get_registry(hass)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/store.py", line 648, in async_get_registry
    return cast(SmartIrrigationStorage, await task)
                                        ^^^^^^^^^^
voluptuous.error.MultipleInvalid: expected float for dictionary value @ data['delta']
```

### Which version are you running?

2024.06.01

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
closing because no diag file attached. please add diag file and reopen
