### ISSUE TITLE
Adding API key crashes Home Assistant / Supervisor issue

### ISSUE THREAD

**Issue by thogens** [jeroenterheerdt/HAsmartirrigation#391]
### What happened?

Hi!
I just updated to the newest version of Smart Irrigation and wanted to add my API key.
That resulted in a frozen HA.
I tried to shutdown my virtual machine.
But I can't reboot. - Getting error message at startup:
`"System in not ready with state: setup"`

-> This boot issue can be fixed by the following commands:
`supervisor repair`
and
`supervisor restart`

### How to reproduce

- Download latest integration 2024.6.1
- enter API key and click confirm
- HA freezes with continues "spinner" -> crash
- bebaut of HA ends in `"System in not ready with state: setup"`

### Relevant log output

```shell
2024-06-06 10:08:50.001 DEBUG (MainThread) [custom_components.smart_irrigation] calling register start event from init
2024-06-06 10:08:50.033 INFO (MainThread) [custom_components.smart_irrigation] Scheduled auto calculate for 23:00
2024-06-06 10:08:50.033 INFO (MainThread) [custom_components.smart_irrigation] Scheduled auto clear of weatherdata for 23:59
2024-06-06 10:08:50.074 INFO (MainThread) [custom_components.smart_irrigation] Updating weather data for all automatic zones
2024-06-06 10:08:50.074 INFO (MainThread) [custom_components.smart_irrigation] Scheduled auto update time interval for each 1:00:00
2024-06-06 10:08:50.374 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Smart Irrigation for smart_irrigation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 139, in async_setup_entry
    await store.set_up_factory_defaults()
  File "/config/custom_components/smart_irrigation/store.py", line 308, in set_up_factory_defaults
    await self.async_factory_default_modules()
  File "/config/custom_components/smart_irrigation/store.py", line 332, in async_factory_default_modules
    inst = m(self.hass, {})
           ^^^^^^^^^^^^^^^^
TypeError: Static.__init__() missing 1 required positional argument: 'config'
```

### Which version are you running?

2024.6.1

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

Unfortunately I can't get the diagnostics file. There is not option to download.

**Comment by jeroenterheerdt** [comment]
should be fixed in v2024.6.3

**Comment by thogens** [comment]
Any quick hint how to download that version? Can't select it...

**Comment by jeroenterheerdt** [comment]
I'd avoid the betas and instead download https://github.com/jeroenterheerdt/HAsmartirrigation/blob/master/custom_components/smart_irrigation/OWMClient.py manually and overwrite the file in your install.

**Comment by thogens** [comment]
I tried option 1 and 2 and both were leading to the same crash.
Currently installed 2024.6.3 ...

**Comment by jeroenterheerdt** [comment]
go back to the one before 2024.6.1 to see if that helps sorry for the inconvenience

**Comment by jeroenterheerdt** [comment]
closing as likely fixed in https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v2024.6.11. Feel free re-open create a new issue if not fixed.

**Comment by thogens** [comment]
Tried 2024.6.12 and it is working now.
