### ISSUE TITLE
voluptuous.error

### ISSUE THREAD

**Issue by maros22** [jeroenterheerdt/HAsmartirrigation#396]
### What happened?

i uninstalled, removed and downloaded again after core update

### How to reproduce

Application not start

### Relevant log output

```shell
Logger: homeassistant.config_entries Zdroj: config_entries.py:594  První výskyt: 10:00:19 (1 výskyty)  Naposledy logováno: 10:00:19
Error setting up entry Smart Irrigation for smart_irrigation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 70, in async_setup_entry
    store = await async_get_registry(hass)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/store.py", line 648, in async_get_registry
    return cast(SmartIrrigationStorage, await task)
                                        ^^^^^^^^^^
voluptuous.error.MultipleInvalid: expected float for dictionary value @ data['delta']
```

### Which version are you running?

v2024.6.3

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[Uploading home-assistant_smart_irrigation_2024-06-08T08-09-01.682Z.log…]()

**Comment by jeroenterheerdt** [comment]
closing - https://github.com/jeroenterheerdt/HAsmartirrigation/discussions/400
