### ISSUE TITLE
initial setup does not work

### ISSUE THREAD

**Issue by fugazzy** [jeroenterheerdt/HAsmartirrigation#405]
### What happened?

initial setup leads to error: (tried versions 2024.6.1 to .8). Errors of version .8 is this:

### How to reproduce

Installation via HACS, restart HA, install integration (with OWM)

### Relevant log output

```shell
Logger: homeassistant.config_entries
Quelle: config_entries.py:594
Erstmals aufgetreten: 09:36:13 (1 Vorkommnisse)
Zuletzt protokolliert: 09:36:13

Error setting up entry Smart Irrigation for smart_irrigation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 145, in async_setup_entry
    await async_register_panel(hass)
  File "/config/custom_components/smart_irrigation/panel.py", line 27, in async_register_panel
    hass.http.register_static_path(PANEL_URL, view_url, cache_headers=False)
  File "/usr/src/homeassistant/homeassistant/components/http/__init__.py", line 428, in register_static_path
    self.app.router.add_route("GET", url_path, serve_file)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py", line 1115, in add_route
    return resource.add_route(method, handler, expect_handler=expect_handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py", line 356, in add_route
    raise RuntimeError(
RuntimeError: Added route will never be executed, method GET is already registered
```

### Which version are you running?

2024.6.8

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

never got a working setup. Can't seem to download diagnostic logs .

**Comment by jeroenterheerdt** [comment]
not sure what is going on here - I have tried multiple times on my machines to uninstall and reinstall - not hitting this error at all. did you uninstall / reboot / reinstall?

**Comment by fugazzy** [comment]
I tried again: Deinstall ans remove from HACS. Reboot HA. Reinstall 2024.6.1, switch to beta and installed 2024.6.9 in HACS. Reboot HA. Install in HA.
That leeds to these errors in logs:
`Logger: homeassistant.config_entries
Quelle: config_entries.py:594
Erstmals aufgetreten: 12:44:16 (1 Vorkommnisse)
Zuletzt protokolliert: 12:44:16

Error setting up entry Smart Irrigation for smart_irrigation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 154, in async_setup_entry
    await store.set_up_factory_defaults()
  File "/config/custom_components/smart_irrigation/store.py", line 308, in set_up_factory_defaults
    await self.async_factory_default_modules()
  File "/config/custom_components/smart_irrigation/store.py", line 342, in async_factory_default_modules
    MODULE_DESCRIPTION: localize(
                        ^^^^^^^^^
TypeError: unsupported operand type(s) for +: 'coroutine' and 'str'`

I verified my OWM-API-key by installing OWM integration. That works fine.
My HA ist on 2024.6.2

**Comment by jeroenterheerdt** [comment]
closing as likely fixed in https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v2024.6.11. Feel free re-open create a new issue if not fixed.

**Comment by fugazzy** [comment]
I can confirm it works now. Thank you!
