### ISSUE TITLE
Error during setup: missing 1 required positional argument: 'config'

### ISSUE THREAD

**Issue by lennon101** [jeroenterheerdt/HAsmartirrigation#408]
### What happened?

I just added this via HACS and after pasting the Openweather API key and hitting submit, the integration showed **Failed to setup** (see below). I checked the logs and it seems there's an error declaring `missing 1 required positional argument: 'config'`. Is this something that I've done or a bug in the integration? Let me know if you need me to do anymore troubleshooting. 

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/1709944/a6180dfe-32e6-4997-8672-2e76f97c5bf0)

### How to reproduce

1. install via HACS (HA running in docker container)
2. paste API key into field and hit submit 
3. observe setup error 

### Relevant log output

```shell
2024-06-14 09:14:04.188 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Smart Irrigation for smart_irrigation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 139, in async_setup_entry
    await store.set_up_factory_defaults()
  File "/config/custom_components/smart_irrigation/store.py", line 308, in set_up_factory_defaults
    await self.async_factory_default_modules()
  File "/config/custom_components/smart_irrigation/store.py", line 332, in async_factory_default_modules
    inst = m(self.hass, {})
           ^^^^^^^^^^^^^^^^
TypeError: PyETO.__init__() missing 1 required positional argument: 'config'
```
```


### Which version are you running?

v2024.6.1

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

Following your instructions to download a diagnostic file is either outdated or not applicable in my case because clicking on those three little dots does not render the option to download this file? See below screenshot

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/1709944/48a7faeb-3086-4a35-b144-f0b6f249a66c)

**Comment by lennon101** [comment]
Following your instructions to download a diagnostic file is either outdated or not applicable in my case because clicking on those three little dots does not render the option to download this file? See below screenshot

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/1709944/48a7faeb-3086-4a35-b144-f0b6f249a66c)

**Comment by jeroenterheerdt** [comment]
revert back to the previous stable release.

**Comment by lennon101** [comment]
> revert back to the previous stable release.

Ok yup that seems to have fixed it for now. Installed version is now **v2024.4.3**. It would appear there is a bug in  **v2024.6.1**.

<img width="560" alt="Screenshot 2024-06-15 at 10 50 27 AM" src="https://github.com/jeroenterheerdt/HAsmartirrigation/assets/1709944/2758c3d5-1bfa-4445-93a5-cce4ca13b452">

**Comment by jeroenterheerdt** [comment]
yes, there is.

**Comment by jeroenterheerdt** [comment]
this should have been fixed in later beta releases, which also have their own issues unfortunately.

**Comment by lennon101** [comment]
Is this project active or truly stale?

**Comment by jeroenterheerdt** [comment]
This project is active. The stale message is because there was no activity on this issue. Try the latest version and let me know if you still having this issue.
