### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by JurajNyiri** [jeroenterheerdt/HAsmartirrigation#427]
### What happened?

Updated from [v2024.4.3](https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v2024.4.3) to [v2024.7.3](https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v2024.7.3).

### How to reproduce

Update from [v2024.4.3](https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v2024.4.3) to [v2024.7.3](https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v2024.7.3).

### Relevant log output

```shell
Error setting up entry Smart Irrigation for smart_irrigation

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 77, in async_setup_entry
    store = await async_get_registry(hass)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/store.py", line 683, in async_get_registry
    data = await task
           ^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

### Which version are you running?

2024.7.3

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

Download Diagnostics is not available as the integration failed setup.

**Comment by JurajNyiri** [comment]
Something must have gone wrong during the update, reverting to 2024.4.3 did not help.

```
Error setting up entry Smart Irrigation for smart_irrigation

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 77, in async_setup_entry
    store = await async_get_registry(hass)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/store.py", line 683, in async_get_registry
    data = await task
           ^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/store.py", line 678, in _load_reg
    await registry.async_load()
  File "/config/custom_components/smart_irrigation/store.py", line 307, in async_load
    inst = m(self.hass, module[MODULE_DESCRIPTION], modconfig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/calcmodules/pyeto/__init__.py", line 84, in __init__
    if CONF_PYETO_FORECAST_DAYS in config and not isinstance(
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```
I will be restoring HA backup.

**Comment by JurajNyiri** [comment]
Attached is smart_irrigation.storage from before the update.

[smart_irrigation.storage.zip](https://github.com/user-attachments/files/16152296/smart_irrigation.storage.zip)

core.config_entries entry looks like this:

```
{
        "data": {
          "owm_api_key": "xxx",
          "owm_api_version": "3.0",
          "use_owm": true,
          "name": "Smart Irrigation"
        },
        "disabled_by": null,
        "domain": "smart_irrigation",
        "entry_id": "b1f7248da6e09f184824a2e6c0e05c65",
        "minor_version": 1,
        "options": {
          "owm_api_key": "xxx",
          "owm_api_version": "3.0",
          "use_owm": true
        },
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "title": "Smart Irrigation",
        "unique_id": "Smart Irrigation",
        "version": 1
      },
```

Restoring the smart_irrigation.storage did not help and the error is still present.

**Comment by jeroenterheerdt** [comment]
Thanks and apologies for this. I tested and upgraded multiple systems from latest beta and latest prod version and didn't find any issues. I will look at this asap

**Comment by jeroenterheerdt** [comment]
should be fixed in next release
