### ISSUE TITLE
[Bug] 0.0.60 error in log 

### ISSUE THREAD

**Issue by ciechompl** [jeroenterheerdt/HAsmartirrigation#43]
**Describe the bug**
yesterday I updated to 0.0.60 ... and noticed this error in log ... just after HA restart

```
2020-07-05 23:36:18 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up smart_irrigation platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 451, in _async_add_entity
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 290, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 317, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/smart_irrigation/sensor.py", line 554, in device_state_attributes
    self.coordinator.show_units,
  File "/config/custom_components/smart_irrigation/helpers.py", line 82, in show_mm_or_inch
    retval = f"{round(value,2)}"
TypeError: type list doesn't define __round__ method
```

**Comment by jeroenterheerdt** [comment]
thanks for reporting - looking at it now

**Comment by jeroenterheerdt** [comment]
fixed in beta release https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v0.0.61
