### ISSUE TITLE
0 data collected 

### ISSUE THREAD

**Issue by cappa88** [jeroenterheerdt/HAsmartirrigation#439]
### What happened?

After the last update, no more data is collected.
This night he therefore did not irrigate despite the high temperatures. And this morning there are still 0 data collected 
![Screenshot_20240713-091315](https://github.com/user-attachments/assets/5d94a296-1038-4d9b-a2a0-9f0c051bf80c)

### How to reproduce

Currently in progress 
[config_entry-smart_irrigation-73ee0f4bb3c39b6f9c7c010022a9f909-4.json](https://github.com/user-attachments/files/16201222/config_entry-smart_irrigation-73ee0f4bb3c39b6f9c7c010022a9f909-4.json)

### Which version are you running?

v2024.7.4

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
Please install 2024.7.5 first and try again.

**Comment by LPX64** [comment]
Hi,
Just updated to 2024.7.5. Got the same issue. I needed to enter OW api key once again but OpenWeather stopped working. In sensors groups OpenWeather is crossed out.
it seems that latest update completely broke this integration.
How can I install 2024.4.3?

**Comment by jeroenterheerdt** [comment]
Clear your browser cache and restart HA. Mostly likely that's the solution. If doesn't help please open your own issue. Saying 'same issue' doesn't help.

**Comment by cappa88** [comment]
I have upgraded to  v2024.7.5.
I activated the new continuous data collection function, Now it would seem to collect data correctly but even tonight the watering time was 0 despite the great heat.
[config_entry-smart_irrigation-73ee0f4bb3c39b6f9c7c010022a9f909-5.json](https://github.com/user-attachments/files/16230313/config_entry-smart_irrigation-73ee0f4bb3c39b6f9c7c010022a9f909-5.json)

**Comment by mistergyle** [comment]
> I have upgraded to v2024.7.5. I activated the new continuous data collection function, Now it would seem to collect data correctly but even tonight the watering time was 0 despite the great heat. [config_entry-smart_irrigation-73ee0f4bb3c39b6f9c7c010022a9f909-5.json](https://github.com/user-attachments/files/16230313/config_entry-smart_irrigation-73ee0f4bb3c39b6f9c7c010022a9f909-5.json)

Try this:
https://github.com/jeroenterheerdt/HAsmartirrigation/issues/435#issuecomment-2227478512

**Comment by cappa88** [comment]
I have everything selected correctly. I only use entities from the weather station 
![Screenshot_20240715-103737](https://github.com/user-attachments/assets/81eb0eb3-f174-4836-a77e-69f716f2b8be)

**Comment by jeroenterheerdt** [comment]
@cappa88 it looks like you are hitting a bug with the continuous data collection feature. can you enable debug logging (for a short period) and post your logs?

**Comment by cappa88** [comment]
That's what I suspected.
I disabled the new feature and everything was working again.
I was also having trouble opening the integration interface.
I will do the test you asked me and I will provide you with the results.

**Comment by cappa88** [comment]
.

**Comment by jeroenterheerdt** [comment]
It's can't parse the home assistant logs but it does collect the info from the home assistant sensors. So I am not sure what you mean exactly. Thanks for providing the files.

**Comment by jeroenterheerdt** [comment]
It can't parse the home assistant logs but it does collect the info from the home assistant sensors. So I am not sure what you mean exactly. Thanks for providing the files.

**Comment by cappa88** [comment]
Did you receive the file? I thought I couldn't load it because it was larger than 2,5GB.

**Comment by jeroenterheerdt** [comment]
Sorry no, I am not seeing any files.

**Comment by cappa88** [comment]
Here is the link where you can download the file.
unfortunately it always generates me a file larger than 2GB even if I do a debug of a few seconds

https://drive.google.com/file/d/1rM0QZxKeCFJl5HHt28dVnHMuN-H7FdBn/view?usp=sharing

I hope it's helpful
Now (11:00 p.m. local time) I launch another debug which I will stop tomorrow morning. 
The calculation should take place at 2:50

**Comment by cappa88** [comment]
https://drive.google.com/file/d/1EX_cFAm18hBHojyjmqV-YCe_PE_5EK7i/view?usp=drive_link
this is tonight's debug.
This time there were no crashes and the calculation was done even though the result seems a bit high to me 

[config_entry-smart_irrigation-73ee0f4bb3c39b6f9c7c010022a9f909.json](https://github.com/user-attachments/files/16319135/config_entry-smart_irrigation-73ee0f4bb3c39b6f9c7c010022a9f909.json)

Another thing to report is that during the turn, while collecting data, I would see the bucket change even far from the time of calculation, 
I hope my feedback is helpful to you

**Comment by cappa88** [comment]
After working one day, it returned a time of 0 s last night.
As can be seen from the diagniostics (attached), a bucket of -6.8 was calculated and a time of 1268s for one zone and 441s for the other.
How is it then that the remained at 0?
Plus the interface seems to crash
![image](https://github.com/user-attachments/assets/68183853-7343-4f13-8f73-4895740e166b)
[config_entry-smart_irrigation-73ee0f4bb3c39b6f9c7c010022a9f909.json](https://github.com/user-attachments/files/16344762/config_entry-smart_irrigation-73ee0f4bb3c39b6f9c7c010022a9f909.json)

**Comment by jeroenterheerdt** [comment]
> After working one day, it returned a time of 0 s last night. As can be seen from the diagniostics (attached), a bucket of -6.8 was calculated and a time of 1268s for one zone and 441s for the other. How is it then that the remained at 0? Plus the interface seems to crash ![image](https://private-user-images.githubusercontent.com/68064795/351214668-68183853-7343-4f13-8f73-4895740e166b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDc4NjEsIm5iZiI6MTcyMjMwNzU2MSwicGF0aCI6Ii82ODA2NDc5NS8zNTEyMTQ2NjgtNjgxODM4NTMtNzM0My00ZjEzLThmNzMtNDg5NTc0MGUxNjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDAyNDYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyYjdlNjM5NTBiYWI4MzQ1MWUzOTAzYzhhY2RkOGQ4MDA0MDE2OTg5NmY1MDk4YzEyOTI5MGZkNTE5MzhhNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-66g1Tba0x0-wN6RduVChjndY-uZ8g_lbITUpj8xhic) [config_entry-smart_irrigation-73ee0f4bb3c39b6f9c7c010022a9f909.json](https://github.com/user-attachments/files/16344762/config_entry-smart_irrigation-73ee0f4bb3c39b6f9c7c010022a9f909.json)

so you still have continuous updates enabled - any chance you can post debug logs?

**Comment by cappa88** [comment]
In these last few days I have disabled continuous collection and everything works fine. 
However, I did not try again with the latest updates.
As soon as I try again I'll let you know

**Comment by cappa88** [comment]
I still can't use continuous data collection.
The result of the calculation is always 0.
[error_log-1.txt](https://github.com/user-attachments/files/16486465/error_log-1.txt)
[config_entry-smart_irrigation-73ee0f4bb3c39b6f9c7c010022a9f909-8.json](https://github.com/user-attachments/files/16486466/config_entry-smart_irrigation-73ee0f4bb3c39b6f9c7c010022a9f909-8.json)

**Comment by jeroenterheerdt** [comment]
thanks, I noticed this in the error log:
```
 File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2122, in async_forward_entry_setup
    _report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1175, in _report_non_awaited_platform_forwards
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 151, in report
    _LOGGER.warning(msg, stack_info=True)
2024-08-03 22:57:53.705 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'battery' when rendering '{{ value_json.battery }}'
2024-08-03 22:57:53.706 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'device_temperature' when rendering '{{ value_json.device_temperature }}'
2024-08-03 22:57:59.469 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{states('sensor.velocita_vento')|float()*(4.87/log((67.8*3.3)-5.42))}}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2258, in forgiving_float_filter
    return float(value)
           ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unavailable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 604, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2639, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2261, in forgiving_float_filter
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1872, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{states('sensor.velocita_vento')|float()*(4.87/log((67.8*3.3)-5.42))}}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 716, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 606, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{states('sensor.velocita_vento')|float()*(4.87/log((67.8*3.3)-5.42))}}' but no default was specified
2024-08-03 22:57:59.476 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{states('sensor.velocita_vento')|float()*(4.87/log((67.8*3.3)-5.42))}}' but no default was specified') while processing template 'Template<template=({{states('sensor.velocita_vento')|float()*(4.87/log((67.8*3.3)-5.42))}}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.vento_a_2m'
```

Seems like a template to convert the windspeed to 2m high is not working?

Also, it looks like your PyETO module has forecast days > 0 so any zones using that module will not be included in the continuous updates, as is shown in the log:
```
2024-08-03 23:01:42.549 INFO (MainThread) [custom_components.smart_irrigation] checked config for PyETO module on zone 3, forecast_days>0, skipping to avoid API calls that can incur costs.
```
Can you check that forecast days is indeed > 0?

**Comment by cappa88** [comment]
If the conversion creates problems I can directly enter the entity of wind, it shouldn't change much

**Comment by jeroenterheerdt** [comment]
No, the issue is the forecast days, that needs to be 0.

**Comment by cappa88** [comment]
It still doesn't work. Now the forecast days are at 0.
I also replaced (to be sure) the entity of the wind with the actual one of the weather station, without the cast at 2 meters.
The problem now is that the calculation is not done at the set time 2:50 AM
https://drive.google.com/file/d/1Jf4kDxvJELIANlf0YD9WFpbBtFTrH5lh/view?usp=drivesdk

**Comment by jeroenterheerdt** [comment]
> It still doesn't work. Now the forecast days are at 0. I also replaced (to be sure) the entity of the wind with the actual one of the weather station, without the cast at 2 meters. The problem now is that the calculation is not done at the set time 2:50 AM https://drive.google.com/file/d/1Jf4kDxvJELIANlf0YD9WFpbBtFTrH5lh/view?usp=drivesdk

Remind me please, do you have continuous updates enabled now? If so, then of course the zones that can be continuously updated and calculated will not be included in the automatic calculation schedule. So if that's what your seeing that is expected.

**Comment by cappa88** [comment]
Now I'm confused. 
Yes, I'm trying to use continuous updates. I thought he still had to make the calculation at the appointed time.
 How should it work then? The bucket always remains at 0 if the calculation is not done

**Comment by jeroenterheerdt** [comment]
continuous updates should update and calculate in real time.

**Comment by cappa88** [comment]
Ok then my problem is that the bucket always remains at 0 despite the data being collected.
![Screenshot_20240809-074237](https://github.com/user-attachments/assets/34596f07-de61-4610-b0d5-d1498d82779b)

**Comment by jeroenterheerdt** [comment]
And you are still using continuous updates, right?

**Comment by cappa88** [comment]
Yes. The supplement is always the continuous update, But the bucket never updates, It always remains at 0.
Now I have momentarily disabled the automation otherwise it would never irrigate. I'm using an automation with set times.

**Comment by cappa88** [comment]
Here is my whole configuration 
![Screenshot_20240809-201042](https://github.com/user-attachments/assets/23e33043-7091-4da6-bf83-341561aa7a3d)
![Screenshot_20240809-201023](https://github.com/user-attachments/assets/aaad41f3-3d3d-4e17-aa3f-94d5f87ebeb8)
![Screenshot_20240809-201028](https://github.com/user-attachments/assets/1b7fc251-ec37-4b48-b539-7835b8e7e83d)
![Screenshot_20240809-201007](https://github.com/user-attachments/assets/ce16e0d1-337e-4c55-a401-e6eb2705286a)

**Comment by jeroenterheerdt** [comment]
Some other users have had success with recreating the zone and sensor group. Not sure why that matters, but can you try to see if that helps at all?

**Comment by cappa88** [comment]
I did this test. I also tried uninstalling the integration.
But nothing: the bucket never updates automatically.
Could I solve this by calling the "Calculate all zones" service at the beginning of the automation?

**Comment by jeroenterheerdt** [comment]
That should not be necessary so yes, that will be a solution but not what should happen. Please bear with me as I try to find the bug.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cappa88** [comment]
Ok. Thank you for the effort you put in. 
So in the meantime I disable continuous updates, so I can use the integration

**Comment by cappa88** [comment]
Since there have been a few updates I have tried re-enabling the continuous updates, but still nothing... it does not update the bucket in real time.
I was going to try uninstalling the integration to reset everything from the beginning, but I can't completely delete the data. 
Once I reinstall from HACS I already find all the old configuration.
How can I do to reinstall the integration as if for the first time?

**Comment by cappa88** [comment]
I attach debug and diagnostic files. I have also tried creating new test zones and new modules and sensor groups
[config_entry-smart_irrigation-01J6HCVJYKBM47NG5NEBYYXGEG.json](https://github.com/user-attachments/files/16816651/config_entry-smart_irrigation-01J6HCVJYKBM47NG5NEBYYXGEG.json)

https://drive.google.com/file/d/1va-rF4WJJBE1LbayoEOO1Rteei1jS6dW/view?usp=sharing

**Comment by jeroenterheerdt** [comment]
It works fine for me, but I can't guarantee the same for your setup

**Comment by jeroenterheerdt** [comment]
That is correct as soon as all of your sensors have sent an updated value the bucket and duration should update

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cappa88** [comment]
@jeroenterheerdt 
Everything seems to be working fine now — the issue looks resolved.

Is weather data still being cleared, or is it now a continuous flow?

I update the bucket by subtracting the actual water delivered (measured with a flow meter) when each irrigation zone turns off:
New bucket = value at shutdown – delivered water

This still seems to align with how continuous updates work. Agree?

I was also thinking of creating a helper that sums daily rain + delivered water, to use instead of the “rain today” sensor.
That way, no need for automations to lower the bucket manually.

Since I have multiple zones, I'd need separate sensor groups.
Not sure how common flow meter usage is in the community, but maybe a “delivered water” entry could be added to sensor groups?

**Comment by jeroenterheerdt** [comment]
Please open an feature request issue for support of flow meters and include the same info as in your last post.
