### ISSUE TITLE
Daily adjusted run time calculation keyerror:day

### ISSUE THREAD

**Issue by scubieman** [jeroenterheerdt/HAsmartirrigation#94]
My hourly runs fine, but my daily wont move off 0 for a few weeks. I searched logs and below is what I found.

File "/config/custom_components/smart_irrigation/sensor.py", line 557, in state
self._state = self.update_state()
File "/config/custom_components/smart_irrigation/sensor.py", line 516, in update_state
self.evapotranspiration = self.get_evapotranspiration(data)
File "/config/custom_components/smart_irrigation/sensor.py", line 689, in get_evapotranspiration
t_day = data["temp"]["day"]
KeyError: 'day'
2022-05-24 07:26:29 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up smart_irrigation platform for sensor

2022-05-24 07:26:28 ERROR (MainThread) [homeassistant.components.input_boolean] Platform input_boolean does not generate unique IDs. ID new_grass_water already exists - ignoring input_boolean.new_grass_water
2022-05-24 07:26:29 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform smart_irrigation

**Comment by schimi42** [comment]
I'm having the same issue since a few days. Is there any solution to this problem?

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 777, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/smart_irrigation/sensor.py", line 557, in state
    self._state = self.update_state()
  File "/config/custom_components/smart_irrigation/sensor.py", line 516, in update_state
    self.evapotranspiration = self.get_evapotranspiration(data)
  File "/config/custom_components/smart_irrigation/sensor.py", line 689, in get_evapotranspiration
    t_day = data["temp"]["day"]
KeyError: 'day'`

**Comment by jeroenterheerdt** [comment]
This should be fixed in the 2.0 beta version (please install and confirm).

**Comment by gatonero** [comment]
This issue no longer exists and should get closed.
